### ISSUE TITLE
Unable to receive the web push from firefox.

### ISSUE THREAD

**Issue by iLexN** [kreait/firebase-php#447] opened 2020-07-06 03:13 UTC
**Describe the bug**
Send a web push, chrome can receive the web push, but firefox can't.
Tested send from the firebase api explorer, both chrome and firefox can receive.

**To Reproduce**
```php
$message = (new Factory)
  ->withServiceAccount($serviceAccountJson)
  ->createMessaging();

$json = '
  {
    "topic": "scmp_exclusive",
    "webpush": {
      "data": {
        "title": "This is title",
        "body": "this is body",
        "icon": "https://cdn.i-scmp.com/sites/default/files/styles/280x224/public/d8/images/methode/2020/05/25/efcaa2a8-9dd4-11ea-96ff-7aff439fc3be_image_hires_005459.JPG?itok=CpJJMZSO",
        "click_action": "https://google.com"
      }
    },
    "fcm_options": {
      "analytics_label": "20200626090654.3085867"
    }
  }
';

$payload = json_decode($json, TRUE);
dump($payload);
$result = $message->send($payload);
dump($result);
```

**Expected behavior**
both chrome and firefox browser can receive the web push.

**Screenshots**
Tested in firebase api explorer with the same payload, both chrome and firefox can receive web push
![image](https://user-images.githubusercontent.com/4638751/86552366-5fa84500-bf7a-11ea-91f1-ac97a4e20a85.png)

**Environment (please complete the following information):**
 - OS: Alpine Linux
 - PHP version: 7.2.31
 - Firebase SDK Version: [4.44.0, 5.5.0"]

**Additional context**

**Comment by jeromegamez** [comment] 2020-07-06 05:15
Unfortunately, I can't reproduce/debug the problem if you don't share the actual payload that you're using.

**Comment by iLexN** [comment] 2020-07-06 06:50
Here is the testing payload

```
{
  "message": {
    "topic": "exclusive",
    "webpush": {
      "data": {
        "title": "This is title",
        "body": "this is body",
        "icon": "https://cdn.i-scmp.com/sites/default/files/styles/280x224/public/d8/images/methode/2020/05/25/efcaa2a8-9dd4-11ea-96ff-7aff439fc3be_image_hires_005459.JPG?itok=CpJJMZSO",
        "click_action": "https://google.com"
      }
    },
    "fcm_options": {
      "analytics_label": "20200626090654.3085867"
    }
  }
}
```

**Comment by jeromegamez** [comment] 2020-07-06 08:22
Thank you for the added information! I used your payload to test it with chrome and with Firefox and it worked on my machine™.

Here are some hints to help hopefully debug this on your side:

**Check if the message arrives at the target browser if sent directly**

```php
use Kreait\Firebase\Messaging\CloudMessage;

$payload = CloudMessage::fromArray($payload)->withChangedTarget('token', $firefoxToken);

$result = $message->send($payload);
dump($result);
```

If the message does arrive in your browser (in subsequent tests, messages took up to 2 minutes to be delivered in my case), the Firefox App Instance might not be subscribed to the given topic. You can check the subscription status with

```php
$appInstance = $messaging->getAppInstance($firefoxToken);
dump($instance->isSubscribedToTopic('scmp_exclusive'));
```

Let me know if this helps

**Comment by iLexN** [comment] 2020-07-07 01:30
Thanks for you information.

Finially , i find that the problem payload.

```
{
    "topic": "scmp_exclusive",
    "webpush": {
      "data": {
        "title": "South China Morning Post",
        "body": "National Security Law: Hong Kong police granted sweeping new powers",
        "icon": "https:\/\/cdn.i-scmp.com\/sites\/default\/files\/styles\/280x224\/public\/d8\/images\/methode\/2020\/07\/07\/a130b5a2-bf9d-11ea-8c85-9f30eae6654e_image_hires_002515.jpg?itok=fuA9VTNC",
        "click_action": "https:\/\/www.scmp.com\/news\/hong-kong\/politics\/article\/3092070\/national-security-law-hong-kong-polices-sweeping-new-powers",
        "nid": "3092070",
        "topic": "'hong_kong' in topics || 'china' in topics"
      }
    },
    "apns": {
      "headers": {
        "apns-priority": "10",
        "apns-topic": "com.scmp.newspulse"
      },
      "payload": {
        "aps": {
          "mutable-content": 1,
          "alert": {
            "title": "National Security Law: Hong Kong police granted sweeping new powers",
            "body": "Hong Kong police granted sweeping new powers"
          }
        },
        "title": "National Security Law: Hong Kong police granted sweeping new powers",
        "body": "Hong Kong police granted sweeping new powers",
        "url": "https:\/\/www.scmp.com\/news\/hong-kong\/politics\/article\/3092070\/national-security-law-hong-kong-polices-sweeping-new-powers",
        "image": "https:\/\/cdn.i-scmp.com\/sites\/default\/files\/styles\/250x250\/public\/d8\/images\/methode\/2020\/07\/07\/a130b5a2-bf9d-11ea-8c85-9f30eae6654e_image_hires_002515.jpg?itok=1-2ctin9",
        "entity_id": "3092070",
        "section_id": "318206",
        "topic_id": "2",
        "alert_topic_name": "Hong Kong,China",
        "alert_topic_display": "National Security Law",
        "uuid": "032ccea0-bf8d-11ea-8c85-9f30eae6654e",
        "action_type": "article",
        "push_time": "20200707000717"
      }
    },
    "android": {
      "priority": "HIGH",
      "restricted_package_name": "com.scmp.newspulse",
      "data": {
        "android_channel_id": "general",
        "title": "National Security Law: Hong Kong police granted sweeping new powers",
        "body": "Hong Kong police granted sweeping new powers",
        "url": "https:\/\/www.scmp.com\/news\/hong-kong\/politics\/article\/3092070\/national-security-law-hong-kong-polices-sweeping-new-powers",
        "image": "https:\/\/cdn.i-scmp.com\/sites\/default\/files\/styles\/250x250\/public\/d8\/images\/methode\/2020\/07\/07\/a130b5a2-bf9d-11ea-8c85-9f30eae6654e_image_hires_002515.jpg?itok=1-2ctin9",
        "entity_id": "3092070",
        "section_id": "318206",
        "topic_id": "2",
        "alert_topic_name": "Hong Kong,China",
        "alert_topic_display": "National Security Law",
        "uuid": "032ccea0-bf8d-11ea-8c85-9f30eae6654e",
        "action_type": "article",
        "push_time": "20200707000717"
      }
    },
    "fcm_options": {
      "analytics_label": "20200707000717.hong_kong.3092070"
    }
  }
```
When the payload has  `android` -> `restricted_package_name` , firefox cannot receive the web push.

after remove the `restricted_package_name`, firefox can receive. 

also tested in firebase api explorer, firefox also cannot receive. and have a message `Property "restricted_package_name" does not exist in object specification.`

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message

the `restricted_package_name` is part fo the adnroid config.

In my case, seem not related to the php package.

**Comment by jeromegamez** [comment] 2020-07-07 07:21
Thank you for sharing this, it certainly will help others facing a similar situation. 🤗

As this is not directly related to the SDK, I'll close the issue, but feel free to add further comments.

**Closed by jeromegamez** 2020-07-07 07:21 UTC
