### ISSUE TITLE
Need to get download url for firebase storage files

### ISSUE THREAD

**Issue by devingDev** [kreait/firebase-php#254] opened 2018-10-15 19:52 UTC
## The problem

Hi I need to get the download-url of the firebase storage file. It looks similiar to this:
https://firebasestorage.googleapis.com/v0/b/myproject.appspot.com/o/somefolder%2Fmyfile.jpg?alt=media&token=a2f6b49d-a817-46d2-ac12-5da312dcd826

You can't just stick the folder and filename to generate the url.
It forbids to download unless you have the correct token.
This url can be fetched in firebase sdk on android and ios afaik and is shown on the webpage if you click on the file and expand the submenu.

## Environment

- PHP Version (`php -v`): 7.2
- Firebase PHP SDK version (`composer show | grep kreait`): 4.17.0

## Code to reproduce issue

**Comment by jeromegamez** [comment] 2018-10-15 20:07
This SDK interfaces to bother the Google Cloud API library as well as Flysystem‘s filesystem, and doesn‘t add functionality on top of them. 

Please refer to https://cloud.google.com/storage/docs/downloading-objects (there is a PHP example in the scripts) and https://github.com/Superbalist/flysystem-google-cloud-storage/

or StackOverflow (although I recommend that you then include a „what I have tried“ section :))

**Comment by jeromegamez** [comment] 2018-10-15 20:40
Here's how I got it to work when I tried it out:

```php
$storage = $firebase->getStorage();

$imageFile = file_get_contents(__DIR__.'/test.jpg');

$uploadedObject = $storage
    ->getBucket()
    ->upload($imageFile, [
        'name' => 'test.jpg'
    ]);

$expiresAt = new \DateTime('tomorrow');

echo $uploadedObject->signedUrl($expiresAt);
```

The `$uploadedObject` instance also has an `->acl()` method, perhaps you could hook into that to make the file public (without making the whole storage public), but I think the example above could perhaps be enough.

Hope it helps!

**Comment by devingDev** [comment] 2018-10-15 20:53
This does work even though its not the same kind of url (the length of it lmao ) and seems to have an expiry date but its cool, I can live with that.
Thank you!

**Comment by jeromegamez** [comment] 2018-10-15 20:58
Could you please try this?

```php
$object = $storage->getBucket()->object('test.jpg');
$object->update(
    ['acl' => []],
    ['predefinedAcl' => 'PUBLICREAD']
);
```

With that, I was able to access my file via 

https://storage.googleapis.com/{project_id}.appspot.com/test.jpg

**Comment by devingDev** [comment] 2018-10-15 21:09
Thanks!
This does indeed work!

 I still wonder if we can somehow get that url with the token at the end. I know I can get it on android and ios iirc and on the project firebase storage page.

**Comment by jeromegamez** [comment] 2018-10-15 21:16
If you find out, please let me know! This is such a common use case that I might add something "native" to the SDK.

I'll close the issue now as it's not a bug per se in the SDK, but please do share your findings in further comments if you'd like!

**Closed by jeromegamez** 2018-10-15 21:16 UTC

**Comment by aqeelhashem** [comment] 2018-12-31 15:58
as i read the solution with  a metadata object nested within the metadata option property. Setting firebaseStorageDownloadTokens to a uuid-v4 value will tell Cloud Storage to use that as its public auth token.

but my problem i can't get the value, i tried with this code but not work to get uuid.

$uuid = $uploadedObject.metadata.firebaseStorageDownloadTokens;

        $ImageUrl = "https://firebasestorage.googleapis.com/v0/b/" + $storage->getBucket() + "/o/" + $filename + "?alt=media&token=" + $uuid;

**Comment by marcus-at-localhorst** [comment] 2019-01-19 09:19
@aqeelhashem here is how you get the token (I stepped through the Firebase Javascript SDK code):

A call (signed with my Firebase Auth Bearer Token!) to `https://firebasestorage.googleapis.com/v0/b/bucket.appspot.com/o/projects%2F-s0m31D%2Fpicture.jpg` returns the following meta data:

```json
{
	"name": "projects/-id/logo.png",
	"bucket": "bucket.appspot.com",
	"generation": "1537960188874518",
	"metageneration": "1",
	"contentType": "image/png",
	"timeCreated": "2018-09-26T11:09:48.874Z",
	"updated": "2018-09-26T11:09:48.874Z",
	"storageClass": "STANDARD",
	"size": "40437",
	"md5Hash": "MxkOU+6feyYtdEAgKbDgp5A==",
	"contentEncoding": "identity",
	"contentDisposition": "inline; filename*=utf-8''picture.jpg",
	"crc32c": "o89Y9dQ==",
	"etag": "CJae8pXE2N0CEAE=",
	"downloadTokens": "32c339ff9-7e4a-42a2-890a-428f8f45d378"
}
```

**EUREKA** there it is, the `downloadTokens`.


Now there are two ways to download the image (or to display it in the browser):

### 1. Authentificate the call with the Firebase Auth Bearer Token

```bash
curl -X GET \
-H "Authorization: Bearer [TOKEN]" \
-o "picture.jpg" \
"https://firebasestorage.googleapis.com/v0/b/bucket.appspot.com/o/projects%2F-s0m31D%2Fpicture.jpg?alt=media"
```

or

### 2. Share publicly with the `downloadTokens` 

```bash
curl -X GET \
-o "picture.jpg" \
"https://firebasestorage.googleapis.com/v0/b/bucket.appspot.com/o/projects%2F-s0m31D%2Fpicture.jpg?alt=media&token=32c339ff9-7e4a-42a2-890a-428f8f45d378"
```

With the `token=xyz` URL parameter, the image is now **available to everyone** who has access to the complete link.


I tried to document my struggle to get media objects referenced in a Firebase Database  from Firebase Storage here: https://marcus-obst.de/blog/firebase-storage-and-firebase-auth#tldr 

So far I was not able to test @jeromegamez library and I found little to no information how to make Firebase Storage work, with my Firebase Authentication Token. I would love somebody with deeper knowledge can comment on this, or if I got everything wrong.
