### ISSUE TITLE
Error while verify token.

### ISSUE THREAD

**Issue by AliHassan13** [kreait/firebase-php#505] opened 2020-11-26 18:16 UTC
i'm using this package it's working fine but When i update my firebase-php (version 5.1.1) i got this error 
`User Deprecated: Not providing the current time is deprecated. Please pass an instance of DateTimeInterface.`
when i call this funtion **$fire_base->verifyIdToken($token);**  i got this error.. how i can fix it?

Environment

OS: ubuntu 20.04
PHP version: 7.3
Firebase SDK Version: 5.1.1

**Comment by jeromegamez** [comment] 2020-11-26 18:19
Duplicate of #504

**Closed** 2020-11-26 18:19 UTC

**Comment by AliHassan13** [comment] 2020-11-26 18:21
@jeromegamez  but i didn't create custom token

**Comment by jeromegamez** [comment] 2020-11-26 18:25
It's the same underlying problem - lcobucci/jwt 3.4 introduces deprecation warnings in several places and I need to handle them :)

**Comment by AliHassan13** [comment] 2020-11-26 18:35
so we have to wait for the new update of **lcobucci/jwt 3.4** and for firebase-php as well?
