### ISSUE TITLE
Transaction Support?

### ISSUE THREAD

**Issue by DPain** [kreait/firebase-php#84] opened 2017-04-23 21:26 UTC
Hi, I'm wondering if there will be transaction support. The page says 100% coverage, but I can't seem to find the transaction feature for Firebase.

Thanks,

**Comment by jeromegamez** [comment] 2017-04-23 21:42
Duplicate of #77 - transactions/promises probably are the same.

In case you mean something like "database transactions" with rollbacks and such, this will not be possible.

By the way: the coverage refers to the code coverage, not the percentage of provided features compared to the official Admin SKDs :).

**Closed by jeromegamez** 2017-04-23 21:42 UTC

**Comment by DPain** [comment] 2017-04-23 21:51
Ah okay thanks for the fast response!
