### ISSUE TITLE
Error while getting the token's user: syntax error from verifyIdToken() method

### ISSUE THREAD

**Issue by nvillaman04** [kreait/firebase-php#744] opened 2022-10-26 17:16 UTC
### Describe the bug

I was trying to make an OTP verification system on my website. But I am getting the below error response from the attached code. I checked the $idToken by printing it. The correct token is coming from the request. But still I am getting the error.

### Installed packages

```json
{
    "name": "kreait/firebase-tokens",
    "description": "A library to work with Firebase tokens",
    "type": "library",
    "keywords": ["firebase", "google", "token", "authentication", "auth"],
    "homepage": "https://github.com/kreait/firebase-token-php",
    "license": "MIT",
    "authors": [
        {
            "name": "Jérôme Gamez",
            "homepage": "https://github.com/jeromegamez"
        }
    ],
    "require": {
        "php": "^7.4|^8.0",
        "ext-json": "*",
        "ext-openssl": "*",
        "fig/http-message-util": "^1.1.5",
        "guzzlehttp/guzzle": "^6.3.1|^7.0",
        "kreait/clock": "^1.1.0",
        "lcobucci/jwt": "^3.4.1|^4.0",
        "psr/cache": "^1.0|^2.0|^3.0",
        "psr/simple-cache": "^1.0.1"
    },
    "suggest": {
        "firebase/php-jwt": "^5.0 can be used to create and parse tokens",
        "guzzlehttp/guzzle": "^6.2.1|^7.0 can be used as an HTTP handler",
        "lcobucci/jwt": "^3.2 can be used to create and parse tokens",
        "psr/cache-implementation": "to cache fetched remote public keys",
        "psr/simple-cache-implementation": "to cache fetched remote public keys"
    },
    "require-dev": {
        "firebase/php-jwt": "^5.3",
        "friendsofphp/php-cs-fixer": "^3.0",
        "phpstan/extension-installer": "^1.1",
        "phpstan/phpstan": "^0.12.88",
        "phpstan/phpstan-phpunit": "^0.12.19",
        "phpunit/phpunit": "^9.5",
        "rector/rector": "^0.11.16",
        "symfony/cache": "^5.3",
        "symfony/var-dumper": "^5.3"
    },
    "autoload": {
        "psr-4": {
            "Kreait\\Firebase\\JWT\\":"src/JWT",
            "Firebase\\Auth\\Token\\": "src/Firebase/Auth/Token"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Firebase\\Auth\\Token\\Tests\\": "tests/Firebase/Auth/Token",
            "Kreait\\Firebase\\JWT\\Tests\\": "tests/JWT"
        }
    },
    "config": {
        "sort-packages": true
    },
    "funding": [
        {
            "type": "github",
            "url": "https://github.com/sponsors/jeromegamez"
        }
    ]
}
{
    "name": "kreait/firebase-tokens",
    "description": "A library to work with Firebase tokens",
    "type": "library",
    "keywords": ["firebase", "google", "token", "authentication", "auth"],
    "homepage": "https://github.com/kreait/firebase-token-php",
    "license": "MIT",
    "authors": [
        {
            "name": "Jérôme Gamez",
            "homepage": "https://github.com/jeromegamez"
        }
    ],
    "require": {
        "php": "^7.4|^8.0",
        "ext-json": "*",
        "ext-openssl": "*",
        "fig/http-message-util": "^1.1.5",
        "guzzlehttp/guzzle": "^6.3.1|^7.0",
        "kreait/clock": "^1.1.0",
        "lcobucci/jwt": "^3.4.1|^4.0",
        "psr/cache": "^1.0|^2.0|^3.0",
        "psr/simple-cache": "^1.0.1"
    },
    "suggest": {
        "firebase/php-jwt": "^5.0 can be used to create and parse tokens",
        "guzzlehttp/guzzle": "^6.2.1|^7.0 can be used as an HTTP handler",
        "lcobucci/jwt": "^3.2 can be used to create and parse tokens",
        "psr/cache-implementation": "to cache fetched remote public keys",
        "psr/simple-cache-implementation": "to cache fetched remote public keys"
    },
    "require-dev": {
        "firebase/php-jwt": "^5.3",
        "friendsofphp/php-cs-fixer": "^3.0",
        "phpstan/extension-installer": "^1.1",
        "phpstan/phpstan": "^0.12.88",
        "phpstan/phpstan-phpunit": "^0.12.19",
        "phpunit/phpunit": "^9.5",
        "rector/rector": "^0.11.16",
        "symfony/cache": "^5.3",
        "symfony/var-dumper": "^5.3"
    },
    "autoload": {
        "psr-4": {
            "Kreait\\Firebase\\JWT\\":"src/JWT",
            "Firebase\\Auth\\Token\\": "src/Firebase/Auth/Token"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Firebase\\Auth\\Token\\Tests\\": "tests/Firebase/Auth/Token",
            "Kreait\\Firebase\\JWT\\Tests\\": "tests/JWT"
        }
    },
    "config": {
        "sort-packages": true
    },
    "funding": [
        {
            "type": "github",
            "url": "https://github.com/sponsors/jeromegamez"
        }
    ]
}
```

### PHP version and extensions

```shell
7.4
```

### Steps to reproduce the issue.

```shell
# Insert the commands issued in the terminal if they are needed
# to reproduce the issue. Otherwise, delete this code block.
```

```php

    $serviceAccount = ServiceAccount::fromValue($jsonFileName);

    $firebase = (new Factory)->withServiceAccount($serviceAccount);

    $firebaseAuth = $firebase->createAuth();

    try {
        
        $token = $firebaseAuth->verifyIdToken($idToken, true);

        $firebaseAuth->revokeRefreshTokens($uid);

    } catch (InvalidToken $e) {

        $result['token'] = $e->getMessage();

    } catch (\Kreait\Firebase\Exception\AuthException $e) {

        $result['token'] = $e->getMessage();

    } catch (\Kreait\Firebase\Exception\FirebaseException $e) {

        $result['token'] = $e->getMessage();
    }
```

### Error message/Stack trace

```shell
Error while getting the token's user: syntax error, unexpected '|', expecting variable (T_VARIABLE)
```

**Comment by jeromegamez** [comment] 2022-10-26 20:02
You posted the contents of the composer.json files from the Firebase libraries, not from your project.

You say the token is correct, but the error shows a PHP syntax error. Something else must be going on there.

Have you confirmed with, for example, https://jwt.io/, that the token contains what you expect it to contain? Please note that token verification only works with ID Tokens generated from one of the client SDKs.

If you are sure this is a bug in the SDK or the Tokens Library, please provide an example with which I can reproduce the problem, thank you 🙏🏻

**Comment by Sukkoth** [comment] 2022-10-26 20:46
I have confirmed my ID token on https:/jwt.io and it is a valid token, but then when I try to verify the token using the package it gives me the same error as @nvillaman04  mentioned. `

syntax error, unexpected '|', expecting ';' or '{' `

How can we solve it?

**Comment by jeromegamez** [comment] 2022-10-26 22:43
Here's the thing - `syntax error, unexpected '|', expecting ';' or '{'` is a PHP error and usually means that the PHP version is too old and cannot process the PHP code. This can happen when you work with a new PHP version locally and an older version remotely.

The SDK and the included dependencies don't have syntax errors, otherwise, the Tests wouldn't even work. Unless you can provide me with more information than just a syntax error from your system, there is not much I can do here. If the token is valid, it must be the environment your project is running in.

I'd also like to remind you that the issue template had clear instructions on what information is expected. Again, you didn't provide me with any information that could help me help you resolve the issue.

As for now, I have to assume that this is not a bug in the SDK, and I will close this issue because of this.

If you can show me how to reproduce the problem, I will have a look again. If you require additional support, [consider becoming a sponsor in one of the _Firebase…_ tiers](https://github.com/sponsors/jeromegamez/). Thank you for your understanding 🙏

**Closed as not planned** 2022-10-26 22:44 UTC
