### ISSUE TITLE
Unable to determine the Firebase Project ID

### ISSUE THREAD

**Issue by uniquespider** [kreait/firebase-php#724] opened 2022-08-04 03:08 UTC
### Describe the feature you would like to see

 hi,Does anyone know why the project_id is wrong? The framework i used is hyperf，version3.0*
```
use Kreait\Firebase\Factory;

public function testFirebase()
    {
        $factory = new Factory();
        $factory->withServiceAccount('my-xxx-firebase-learn-firebase-adminsdk-59959.json')
            ->withProjectId('my-xxx-firebase-learn')
            ->withDatabaseUri('https://my-xxx-firebase-learn-xxx-rtdb.firebaseio.com');
        $realTimeDb = $factory->createDatabase();
        $reference = $realTimeDb->getReference('apps/');
        var_dump($reference);
    }
```
postman :
```
{"code":0,"message":"Unable to determine the Firebase Project ID","data":null}
```

**Comment by uniquespider** [comment] 2022-08-04 03:16
the project_id i found in the firebase project settings/general。And it is consistent with the project_id in key.json

**Comment by uniquespider** [comment] 2022-08-04 03:48
After debugging, it is found that the package installed by composer lacks the Clock component, and other unknown components，for example，lacks firebase-tokens/src/Firebase。
I don't know why this happens？
my composer `repositories.packagist.org.url`  is `https://repo.packagist.org`

**Comment by jeromegamez** [comment] 2022-08-04 06:01
Hey there 👋

Could you please try doing a `composer update -with-all-dependencies` - when dependencies are missing this is my go-to solution 🤞

If that doesn't work, please check if composer shows any conflicts - if there are none, please share your PHP and composer version and the composer.json.

**Comment by uniquespider** [comment] 2022-08-04 06:35
> Hey there 👋
> 
> Could you please try doing a `composer update -with-all-dependencies` - when dependencies are missing this is my go-to solution 🤞
> 
> If that doesn't work, please check if composer shows any conflicts - if there are none, please share your PHP and composer version and the composer.json.

thank you for reply,
I tried your way，but there is difficult here. my local develop environment `composer 2.3.9, php 8.0.2, firebase-php 5.6.23`, my server environment `composer 2.3.5, php 8.1, firebase-php 6.7`; There is currently no time to sync these environments，
I plan to keep firebase-php:5.6.23 first.

thank you.

**Comment by jeromegamez** [comment] 2022-08-04 06:51
This is very clearly nothing I can support you with here, sorry. You're using different PHP, composer AND library versions in your two environments, no wonder this is causing trouble.

I strongly recommend taking the time to sync your environments and to use the same dependencies everywhere.

I have to close this issue because it's not caused by a bug in the SDK.

**Closed as not planned** 2022-08-04 06:51 UTC
