### ISSUE TITLE
can this work in multiple arduino devices and send data simultaneously  to connect in a single php code to firebase?

### ISSUE THREAD

**Issue by xiaomy12** [kreait/firebase-php#287] opened 2019-03-10 13:28 UTC
Please avoid using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a help channel at https://gitter.im/kreait/firebase-php (you can sign in with your GitHub account). If nobody can answer your question, tag @jeromegamez in your question.

Also see past issues and https://firebase-php.readthedocs.io/en/latest/troubleshooting.html to check if your problem has already been covered.

Please chose a descriptive title for your issue and delete everything before and including this line before submitting the issue.

## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added). 

## Environment

- PHP Version (`php -v`):
- Firebase PHP SDK version (`composer show | grep kreait`):

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code to reproduce issue

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by jeromegamez** [comment] 2019-03-10 14:17
Duplicate of #285

You have asked this question already, and I answered I’d already: there is no reason why this shouldn‘t work.

Next time, please read and follow the issue template. 

(You can add more comments even if an issue is closed)

**Closed by jeromegamez** 2019-03-10 14:17 UTC

**Comment by xiaomy12** [comment] 2019-03-10 14:41
I don't yet use your library sir because I don't know how to put it in my web server 00webhost
which specific file/s? I had used ktamas77 it only requires the firebaseLib and the php code
but that one doesn't work on sending the data simultaneously with 3 arduino devices
sorry too because I didn't notice your comment on 285

**Comment by xiaomy12** [comment] 2019-03-10 14:50
@jeromegamez sir I need your help

**Comment by xiaomy12** [comment] 2019-03-10 15:12
@jeromegamez sir pls help me I've been solving the problem since 2 months ago and now I finally decided to use your lbrary

**Comment by xiaomy12** [comment] 2019-03-11 01:21
sir I have 3 arduino devices those are connected in 1 php code (web server) to firebase
but the connection is not simultaneously sending data it only allows 1 device to be updated in firebase
so I ask how to use your library 
which file I should download to my web server so that it could work with my desire
I hope you would reply sir thank you!

**Comment by xiaomy12** [comment] 2019-03-11 01:21
@jeromegamez @morrislaptop @wadewomersley @MGParisi

**Comment by jeromegamez** [comment] 2019-03-11 08:08
Spamming will not result in faster responses (especially not on sundays 😉).

So, if I understand you correctly, you have 1 web server and 3 arduino devices connecting to that webserver, but the actual problem is that you don't know how to install the Firebase SDK on your webserver?

To be able to use this SDK, you must install it with composer in your project, see https://firebase-php.readthedocs.io/en/latest/overview.html#installation

After the installation, you need to set the project up as described in https://firebase-php.readthedocs.io/en/latest/setup.html

Unfortunately, I'm not able to provide support for basic usage of PHP and/or Composer.

**Comment by xiaomy12** [comment] 2019-03-11 13:39
good evening sir 
sorry for spam messages
yes have 1 web server and 3 arduino devices connecting to that webserver
but only one devices is updating and those 2 devices are not updating

but when another device is on (it will update) but the recent one will stop updating
I've been finding and solving this problem for 2 months but I had no solution
I hope you can help me sir
so I tried to use your library

**Comment by jeromegamez** [comment] 2019-03-11 13:46
Please try creating 3 separate Service Account JSON files for each of your Arduinos. It could be that API is rejecting the simultaneous requests from different machines.

You can create new Service Account JSON files by following the instructions on https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app - if you follow the instructions, click on "Generate new private key" once for every machine you use.

**Comment by xiaomy12** [comment] 2019-03-11 13:48
I will insert it for my php code?

**Comment by jeromegamez** [comment] 2019-03-11 13:52
If you follow the steps, you will have three different JSON-Files with different contents. Upload each file to each Arduino and put them in `/path/to/service-account.json` (<- this is just an example, use the path that you have configured in your code).

```php
$serviceAccount = ServiceAccount::fromJsonFile('/path/to/service-account.json');
```

This will then load the different credentials on each of your arduinos.

**Comment by jeromegamez** [comment] 2019-03-11 13:54
It's really difficult to help without knowing *what* you actually tried, which code you used and what specific error you received. Unfortunately "It doesn't work" doesn't really help, and I can only guess what's not working.

**Comment by xiaomy12** [comment] 2019-03-11 13:56
here's my code

<?php require 'firebaseLib.php'; $Trash = $_GET["trash"]; $Distance = $_GET["distance"]; $Temperature = $_GET["temp_f"]; $Humidity= $_GET["humidity"]; $url = 'https://thesis1-69.firebaseio.com'; $token = 'xxxxxxxxxxxxxxxx'; $firebasePath = '/thesis1-69/'; $devicestatus= array('Distance' => $Distance,'Temperature' => $Temperature,'Humidity' => $Humidity); $full= array($Trash => $devicestatus); $fb = new Firebase($url, $token); $fb -> update($firebasePath, $full); ?>

**Comment by xiaomy12** [comment] 2019-03-11 13:59
as you can see the $trash is the ID for each arduino devices
and each has 3 data = temperature/humidity and distance

**Comment by xiaomy12** [comment] 2019-03-11 13:59
I can't use SDK for my php code

**Comment by jeromegamez** [comment] 2019-03-11 14:02
`$fb = new Firebase($url, $token);` will indeed not work. You can't just replace ktamas77/firebase-php with this one, the two libraries are not compatible.

**Comment by xiaomy12** [comment] 2019-03-11 14:06
so that was the problem? I just follow this one https://stilllot2learn.wordpress.com/2017/11/18/arduino_gps_gsm/comment-page-1/?unapproved=59&moderation-hash=18f8805dfbae01d1dfc05abf2485259a#comment-59

**Comment by jeromegamez** [comment] 2019-03-11 14:12
The problem is that the code from the page is meant for ktamas77/firebase-php, not for this library. In order to use the PHP SDK from this repository, you will have to refactor the code.

I'm sorry, but I can't give support for another library here 😅

That said, you could try creating three separate database secrets to use with your three arduino devices.

Go to https://console.firebase.google.com/u/0/project/_/settings/serviceaccounts/databasesecrets and create two new database secrets.

Then, use `$fb = new Firebase($url, $token)` with the different tokens.

**Comment by xiaomy12** [comment] 2019-03-11 14:15
sorry sir
yes I understand
thank you sir


but  I already tried creating another database secret or tokens for other device but recently it doesn't work

**Comment by xiaomy12** [comment] 2019-03-11 14:36
I tried it again and still no good
