### ISSUE TITLE
500 page error version 5

### ISSUE THREAD

**Issue by vitalijalbu** [kreait/firebase-php#418] opened 2020-04-29 09:40 UTC
**Describe the bug**
My page gives 500 error

**To Reproduce**
A self-contained code example to reproduce the behavior

```php
require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

// This assumes that you have placed the Firebase credentials in the same directory
// as this PHP file.
$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/ceebo-partner-firebase-adminsdk-d0l2q-4e663c2b68.json');
$firebase = (new Factory)
   ->withServiceAccount($serviceAccount)
   ->withDatabaseUri('https://ceebo-partner.firebaseio.com/')
   ->create();
$database = $firebase->getDatabase();
```

**Expected behavior**

**Screenshots**
<img width="584" alt="Schermata 2020-04-29 alle 11 37 30" src="https://user-images.githubusercontent.com/40239902/80581853-1aade280-8a0e-11ea-87e9-e5e6f1060ae5.png">

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, MacOS 10.14, Ubuntu 18.04, ...]
 - PHP version: [e.g. 7.3.8]
 - Firebase SDK Version: [e.g. 4.28, **not** "latest"]

**Additional context**

**Comment by jeromegamez** [comment] 2020-04-29 09:56
Duplicate of #408, #410, #415

You’re on a `5.x` release and are using 4.x methods that have been deprecated a long time ago and removed in 5.0.

Please read and follow the documentation at https://firebase-php.readthedocs.io/en/stable/setup.html

**Closed by jeromegamez** 2020-04-29 09:56 UTC
