### ISSUE TITLE
Error creating resource, Connection timed out

### ISSUE THREAD

**Issue by miclaus** [kreait/firebase-php#176] opened 2018-03-03 18:02 UTC
#### 1. Which version of `kreait/firebase-php` are you using?
`kreait/firebase-php@4.1.2`

`guzzlehttp/guzzle@6.3.0`

#### 2. Which version of PHP are you using?
`PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )`

#### 3. What's the issue?
My code suddently stopped working with `kreait/firebase-php@3.1` – probably because of Firebase changes/deprecations – so I thought I'll do an update. I updated to `4.1.2` generated new Firebase Service Account credentials. Then I replaced the deprecated `asUserWithClaims` method with `asUser` instead. On my local machine everything worked fine, but online I can't seem to be able to request the data.

After surrounding my code (see section 4) with a `try catch` block, i receive the following Exception:

```
Exception:
Error creating resource: [message]
fopen(https://PROJECT_ID.firebaseio.com/PATH_TO_RESSOURCE.json?
auth_variable_override=%7B%22uid%22%3A%22MY_ADMIN_UID%22%7D): failed to open stream:
Connection timed out [file]
/var/www/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line] 324
```

#### 4. Code that lead to the issue

**NOTE** that I've replaced some sensitive data:

```php
<?php

require_once 'vendor/autoload.php';
require_once 'constants.php';

// debugging
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

try {
  // Firebase Admin SDK
  $serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/__my_private_credentials__.json');
  $firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->asUser(MY_ADMIN_UID) // from constants.php
    ->create();
  $database = $firebase->getDatabase();

  $projectPath = PATH_TO_RESSOURCE; // from constants.php
  $projectRef = $database->getReference($projectPath);
  $projectData = json_decode( json_encode($projectRef->getValue()) );

  echo '<pre>';
  var_dump($projectData);
  echo '</pre>';

} catch(Exception $e) {
  echo 'Exception:<br>';
  echo $e->getMessage();
}

exit;
```

## Guesses
I can only guess what's wrong here... Maybe because we use SSL on the server ?
Or do I require an API key from firebase and use `withServiceAccountAndApiKey` instead ?

What are your guesses ?
It would be awesome to get a lead on this issue, since we use this in production...

Thanks in advance !

**Comment by jeromegamez** [comment] 2018-03-03 18:14
Hey @miclaus, and thanks for the detailed issue description!

Looking at the error, it seems as if Guzzle is using `fopen()` to send the requests - I have only tested the library with the curl library installed so I can't test this at the moment, but if possible, could you make sure that curl and the `php-curl` packages are installed on the system and try if this helps?

**Comment by jeromegamez** [comment] 2018-03-03 18:17
Not related to the issue at hand:

The api key is not needed anymore (it probably never was 😅), so you can safely remove it from your environment(s).

Also, just to make sure that we are on the same page: if your user with with the `MY_ADMIN_UID` is allowed to do anything on your realtime database, you could consider just dropping it altogether, because thanks to the service account credentials, you have admin permissions by default.

**Comment by miclaus** [comment] 2018-03-03 18:27
@jeromegamez okay thanks for the tipps, I'll try some things out and report back.

also thanks for the admin tipp, didn't know that ! the user actually is permitted to do both read and write, since i've set the Database rules to the following:

```json
{
  "rules": {
    ".read": "auth != null && auth.uid === 'MY_ADMIN_UID'",
    ".write": "auth != null && auth.uid === 'MY_ADMIN_UID'"
  }
}
```

i guess i'll just have to remove the `&& auth.uid ...` part when not using `asUser(MY_ADMIN_UID)` ?

**Comment by jeromegamez** [comment] 2018-03-03 18:32
Depends - you don't need the check for your requests through the Firebase SDK because the security rules don't apply to the service account - but as far as I see, if you change it to `auth != null` only, any authenticated user can read an write everything.

**Comment by miclaus** [comment] 2018-03-03 18:50
ah right ! now i remembered why we check for UID.

**Comment by miclaus** [comment] 2018-03-03 19:07
@jeromegamez okay, so after `sudo apt-get install php-curl` and restarting the server, I now get a more lean Exception error from cURL:

```
cURL error 7: Failed to connect to PROJECT_ID.firebaseio.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

following the link, i got the following description on error 7:
```
CURLE_COULDNT_CONNECT (7)
  Failed to connect() to host or proxy.
```

just for the record, my `php.ini` does reflect `allow_url_fopen = On` and I've also tried manually setting `ini_set('allow_url_fopen', 1);` but that didn't work either.

**Comment by jeromegamez** [comment] 2018-03-03 19:26
Does `curl -I -XGET https://PROJECT_ID.firebaseio.com/.json` work? You should get a `401 Unauthorized` response.

If you get a 404, the project id in your service account JSON file does not match the database uri, which you could then check in your Firebase project's Database section and override with

```php
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->withDatabaseUri($valueFromConsole);
```

If the connection doesn't work at all, it has to be some other issue on the server, my first attempt would be to ensure the latest versions of OpenSSL and php-openssl.

**Comment by miclaus** [comment] 2018-03-03 19:44
`curl` gives me `curl: (7) Failed to connect to PROJECT_ID.firebaseio.com port 443: Connection timed out` same as in the browser. i do however get a `401 Unauthorized` when i request https://PROJECT_ID.firebaseio.com/.json in the browser – so the PROJECT_ID should be right.

current OpenSSL is 1.0.2g 1 Mar 2016 according to phpinfo. i'll see what i can do here, but i might also have to update PHP for this...

**Comment by jeromegamez** [comment] 2018-03-07 18:10
@miclaus Have you been able to solve the issue?

**Comment by miclaus** [comment] 2018-03-08 09:04
@jeromegamez i'm waiting for my colleague to renew the SSL certificate.

meanwhile, i tried the same procedure on my local machine and the connection to Firebase and everything else worked just fine.

in case it's the unverifiable SSL certificate a more descriptive error would be cool.

**Comment by jeromegamez** [comment] 2018-03-08 09:50
If there was an issue with the SSL certificate it self, the error would be more descriptive already, because the Request itself would not have been issued (see also https://firebase-php.readthedocs.io/en/latest/troubleshooting.html#curl-error-xx-ssl-certificate-validation-failed). I'm not entirely sure the certificate is the issue, and I haven't be able to reproduce the problem so far :/

**Comment by miclaus** [comment] 2018-03-08 10:13
@jeromegamez hmm, i'm not 100% sure either... we have a SSL certificate, however when i `wget` something on the server i get the error that the "certificate common name '[SERVER_DOMAIN]' doesn't match the requested host name '[SERVER_IP]'.

thanks for the link, that's what i would have expected !
i'll let you know as soon as i know more.

**Comment by jeromegamez** [comment] 2018-03-08 19:15
I will close the issue now because it is not directly linked to the library (BTW: I just released [4.2.0](https://github.com/kreait/firebase-php/releases/tag/4.2.0) 🎉), but please let me know if you resolved the issue - just because it's closed for me doesn't mean I'm not interested :)

**Closed by jeromegamez** 2018-03-08 19:15 UTC

**Comment by miclaus** [comment] 2018-03-09 13:39
sure :) thanks for your support on this one !

and congratz to 4.2.0 ! 🎉

**Comment by miclaus** [comment] 2018-03-12 10:51
@jeromegamez unfortunately still no work after SSL renewal and switch to domain name :/

is there a possibility to increase the call `expiry` timeout ?

i've noticed that I receive the error after exactly 1 minute.

**Comment by jeromegamez** [comment] 2018-03-12 11:43
Not without a fork of the library, unfortunately, at least not at the moment - I will see if I can open up the HTTP settings... On the other hand: do you really want to wait over a minute per request? 😅

**Comment by miclaus** [comment] 2018-03-12 11:54
@jeromegamez yeah, actually it's not such a great idea.. i tried the same connection on my local machine and it took only ~13sec.

it's weird since, i can curl google with no prob, but can't curl a specific reference from my Firebase project URL – keep getting "Connection timed out".

Firewall is also disabled and i even tried using `file_get_contents` without any Firebase Database Rules, still no success...

by now, i can surely say that the issue is not with your lib. 😄

**Comment by miclaus** [comment] 2018-03-12 12:27
@jeromegamez thanks for you time and interest !

we finally found the issue why the connection couldn't be established – it was a configuration thingy on the router ... **tracing the route**, unveiled the issue.

your library already did what it should ! :)
