### ISSUE TITLE
verifyIdToken() fails

### ISSUE THREAD

**Issue by sdwru** [kreait/firebase-php#506] opened 2020-11-26 20:43 UTC
This started happening after a composer update.  No changes were made to the php code which was working fine before.  So it must be because of a package update as far as I can tell.  Either `firebase-php` or a `google cloud` package update.  I re-checked the official firebase-php documentation. Usage of `verifyIdToken()` is still the same according to that documentation.
```
try {

 $token = $request->bearerToken();
 $verifiedToken = $this->auth->verifyIdToken($token);

catch {
 echo $e->getMessage();
}
```
Results in the following caught error.

_"The token has an invalid signature: Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes."_

That is a laravel v8 request response.  It comes directly from the Firestore auth response and looks like the usual bearer token response.  I can't imagine why Firestore would suddenly be sending me invalid bearer tokens and I don't see any recent changes to that kreait/firebase-php `verifyIdToken()` function.

**Comment by jeromegamez** [comment] 2020-11-26 21:15
Duplicate of #504 and and #505

**Closed** 2020-11-26 21:23 UTC
