### ISSUE TITLE
$reference->getData() is always blocked

### ISSUE THREAD

**Issue by HungChu** [kreait/firebase-php#25] opened 2016-07-15 09:42 UTC
Here is my code:

```php
$config = new Configuration();
$config->setAuthConfigFile('path/to/json');

$firebase = new Firebase('https://my_project_id.firebaseio.com', $config);

$reference = $firebase->getReference("path/to/location");

$data = $reference->getData(); // <-- always blocked here
```

I tried this way equivalent by java (on the same json & firebase_url) then everything worked fine.

**Comment by jeromegamez** [comment] 2016-07-15 10:02
Thank you for taking the time to report this issue - unfortunately, the Firebase V3 SDK integration is not working as I hoped with this library, #24 describes another issue with the service account configuration not working properly.

For now, I would recommend to use the Firebase Secret method (you can find the secret at https://console.firebase.google.com/project/my-project-id/settings/database ), but I am currently working on a (PHP 7) rewrite of the library, explicitely targeted at being used with service accounts - would you be open to use this as soon as it is ready?

**Comment by HungChu** [comment] 2016-07-15 10:35
Yes, It is solved by using Secret method. Thank you!

**Comment by jeromegamez** [comment] 2016-07-15 10:39
Happy it works! I will close this issue now, but of course, feel free to re-open it or create a new one at any time!

**Comment by jeromegamez** [comment] 2016-07-15 14:52
@HungChu I just released a new patch version, see https://github.com/kreait/firebase-php/releases/tag/0.10.2

Using the Google Service Account should now work as expected - I would be happy if you would like to test this and give me feedback if it works for you as well.

**Comment by HungChu** [comment] 2016-07-17 09:45
Sorry about my late.

Before, I tested on PHP v5.4.x by using the Google Service Account so the line $data = $reference->getData(); is alway blocked. After that, I changed to Firebase Service method according to your suggestion but it was warned by curl. So i thought that it happened by i used the old php version

Today, I re-test by using Firebase Secret method on PHP v5.5.34, it always pass from line ->getData() but it always be halt on that (don't execute any line code after that point). The problem is happening the same with the Google Service Account method.

I applied your new path version but the problem is still unresolved.

**Comment by jeromegamez** [comment] 2016-07-17 11:04
This is strange - if a HTTP request to Firebase fails, an exception should be thrown. Can you please check the following:

- Is there a custom exception handler set in your project or another setting that prevents exceptions or hides them?
- Are you using the latest Version of this library? see https://github.com/kreait/firebase-php/releases
- Could you configure the library with a logger to see if any errors are shown there? You can find the [Logging documentation here](http://firebase-php.readthedocs.io/en/latest/configuration.html#logging)

:octocat:

**Comment by HungChu** [comment] 2016-07-17 13:49
Thanks @jeromegamez !

I try/catch that lines code then caught the exception: Permission denied.

After that, I tried to run the java program again with the same url & account service then get the fine result.

So I guest that the authentication to firebase service with ssl (account service) has a problem?

**Comment by jeromegamez** [comment] 2016-07-17 14:12
Thanks for trying out! Could you show me the PHP-code you are using to perform the request, please? I will then try to reproduce the error.

Are you using the same Service Account for your PHP and Java apps?

And did you make sure to update to version 1.0.1?

**Comment by HungChu** [comment] 2016-07-18 01:49
Yes, I updated lib to version 1.0.1.

Here is my Google Service Account (plz change the ext from .txt to .json:

[thtt_credentials.txt](https://github.com/kreait/firebase-php/files/368241/thtt_credentials.txt)


And, here is my code that is using it:

<?php

include_once '../vendor/autoload.php';

use Kreait\Firebase\Configuration;
use Kreait\Firebase\Firebase;

$config = new Configuration();
$config->setAuthConfigFile('thtt_credentials.json');

$firebase = new Firebase('https://thtt-c7be6.firebaseio.com', $config);

$thtt = $firebase->getReference("THTT");
$users = $thtt->getReference("users");
$my = $users->getReference('1');
$state = $my->getReference("state");

echo $state->getKey();
echo ": ";
try
{
    $data = $my->getData();
    print_r($data);
} catch (Exception $ex)
{
    echo $ex->getMessage(); // Permission deined
}

echo "<br>Done!";

**Comment by jeromegamez** [comment] 2016-07-18 17:17
@HungChu Sorry for the late reply, first day of regular work today for me :).

I have deleted the credentials file from your comment to avoid others being too curious - but thanks for being so open with it.

I tested your script with your service account and everything worked as it should (I just replaced the `print_r()` with `var_dump()` to make sure that I see boolean/null values.

Could you please show me an output of a `php -m` command on your computer? My first thought when I got it working, was that you might not have the `openssl` extension installed so that requests to the HTTPS domain of a firebase app might not be performed correctly.

Could this be possible?

**Comment by HungChu** [comment] 2016-07-19 03:42
Yes, here is the output for the command:
$ php -m

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
hash
iconv
json
ldap
libxml
mbstring
mysql
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]

**Comment by jeromegamez** [comment] 2016-07-20 09:04
@HungChu I am really out of ideas, but I still think this is not a problem of the library, but of the system environment you're running the script in.

So, I will close the issue, since it seems not to be in scope of this library - but please do add comments if you figured out what the problem is, or try one of the other firebase libraries from https://packagist.org/search/?q=firebase-php - perhaps it will work with one of them.

Sorry I couldn't really help so far!

**Closed by jeromegamez** 2016-07-20 09:04 UTC
