### ISSUE TITLE
Missing multi factor information when fetching user records

### ISSUE THREAD

**Issue by jesperbjerke** [kreait/firebase-php#749] opened 2022-11-29 07:48 UTC
### Describe the feature you would like to see

Currently, the section with information about enrolled multi factors on a user does not get returned in the UserRecord.

https://firebase.google.com/docs/auth/admin/manage-mfa-users#getting_users

Dumping the raw data in \Kreait\Firebase\Auth\UserRecord::fromResponseData seems to have it though.
Would be nice to be able to retrieve this.

**Comment by jeromegamez** [comment] 2022-11-29 07:53
This will be included in the upcoming 7.0 release - if you'd like, you can use the 7.x branch until then, it's already in there. I don't have MFA-enabled users in my test project, so it would be nice as a test that everything works as intended as well 🙏🏻

**Comment by jeromegamez** [comment] 2022-12-20 17:28
Version 7.0 of the SDK has just been released and user records now should include the MFA information! 🚀🥳

I'm closing this issue now, but please make sure to let me know if something doesn't work!

**Closed as completed by jeromegamez** 2022-12-20 17:28 UTC
