### ISSUE TITLE
Hosting not working

### ISSUE THREAD

**Issue by heeshala** [kreait/firebase-php#643] opened 2021-07-24 15:07 UTC
### Describe the issue you are experiencing

When hosting the files in Cpanel the php pages that do connect with firebase are not working 

HTTP ERROR 500

### Installed packages

brick/math                 0.9.2   Arbitrary-precision arithmetic library
fig/http-message-util      1.1.5   Utility classes and constants for use with PSR-7 (psr/http-message)
firebase/php-jwt           v5.4.0  A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should co...   
google/auth                v1.16.0 Google Auth Library for PHP
google/cloud-core          v1.42.2 Google Cloud PHP shared dependency, providing functionality useful to all com...   
google/cloud-firestore     v1.19.3 Cloud Firestore client for PHP
google/cloud-storage       v1.24.1 Cloud Storage Client for PHP
google/common-protos       1.3.1   Google API Common Protos for PHP
google/crc32               v0.1.0  Various CRC32 implementations
google/gax                 v1.7.1  Google API Core for PHP
google/grpc-gcp            0.1.5   gRPC GCP library for channel management
google/protobuf            v3.17.3 proto library for PHP
grpc/grpc                  1.39.0  gRPC library for PHP
guzzlehttp/guzzle          7.3.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises        1.4.1   Guzzle promises library
guzzlehttp/psr7            1.8.2   PSR-7 message implementation that also provides common utility methods
kreait/clock               1.1.0   A PHP 7.0 compatible clock abstraction
kreait/firebase-php        5.19.0  Firebase Admin SDK
kreait/firebase-tokens     1.15.0  A library to work with Firebase tokens
lcobucci/jwt               3.4.5   A simple library to work with JSON Web Token and JSON Web Signature
monolog/monolog            2.3.2   Sends your logs to files, sockets, inboxes, databases and various web services     
mtdowling/jmespath.php     2.6.1   Declaratively specify how to extract elements from a JSON document
psr/cache                  1.0.1   Common interface for caching libraries
psr/http-client            1.0.1   Common interface for HTTP clients
psr/http-message           1.0.1   Common interface for HTTP messages
psr/log                    1.1.4   Common interface for logging libraries
psr/simple-cache           1.0.1   Common interfaces for simple caching
ralouphie/getallheaders    3.0.3   A polyfill for getallheaders.
ramsey/collection          1.1.3   A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                4.1.1   A PHP library for generating and working with universally unique identifiers ...   
riverline/multipart-parser 2.0.8   One class library to parse multipart content with encoding and charset support.    
rize/uri-template          0.3.3   PHP URI Template (RFC 6570) supports both expansion & extraction
symfony/polyfill-ctype     v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring  v1.23.0 Symfony polyfill for the Mbstring extension

### PHP version and extensions

composer-plugin-api    2.0.0      The Composer Plugin API
composer-runtime-api   2.0.0      The Composer Runtime API
ext-bcmath             7.3.27     The bcmath PHP extension
ext-bz2                7.3.27     The bz2 PHP extension
ext-calendar           7.3.27     The calendar PHP extension
ext-ctype              7.3.27     The ctype PHP extension
ext-curl               7.3.27     The curl PHP extension
ext-date               7.3.27     The date PHP extension
ext-dom                20031129   The dom PHP extension
ext-exif               7.3.27     The exif PHP extension
ext-fileinfo           7.3.27     The fileinfo PHP extension
ext-filter             7.3.27     The filter PHP extension
ext-ftp                7.3.27     The ftp PHP extension
ext-gd                 7.3.27     The gd PHP extension
ext-gettext            7.3.27     The gettext PHP extension
ext-grpc               1.39.0     The grpc PHP extension
ext-hash               7.3.27     The hash PHP extension
ext-iconv              7.3.27     The iconv PHP extension
ext-json               1.7.0      The json PHP extension
ext-libxml             7.3.27     The libxml PHP extension
ext-mbstring           7.3.27     The mbstring PHP extension
ext-mysqli             7.3.27     The mysqli PHP extension
ext-mysqlnd            0          The mysqlnd PHP extension (actual version: mysqlnd 5.0.12-dev - 20150407 - $Id...   
ext-openssl            7.3.27     The openssl PHP extension
ext-pcre               7.3.27     The pcre PHP extension
ext-pdo                7.3.27     The PDO PHP extension
ext-pdo_mysql          7.3.27     The pdo_mysql PHP extension
ext-pdo_sqlite         7.3.27     The pdo_sqlite PHP extension
ext-phar               7.3.27     The Phar PHP extension
ext-readline           7.3.27     The readline PHP extension
ext-reflection         7.3.27     The Reflection PHP extension
ext-session            7.3.27     The session PHP extension
ext-simplexml          7.3.27     The SimpleXML PHP extension
ext-spl                7.3.27     The SPL PHP extension
ext-tokenizer          7.3.27     The tokenizer PHP extension
ext-wddx               7.3.27     The wddx PHP extension
ext-xml                7.3.27     The xml PHP extension
ext-xmlreader          7.3.27     The xmlreader PHP extension
ext-xmlwriter          7.3.27     The xmlwriter PHP extension
ext-zip                1.15.4     The zip PHP extension
ext-zlib               7.3.27     The zlib PHP extension
lib-bz2                1.0.8      The bz2 library
lib-curl               7.70.0     The curl library
lib-curl-libssh2       1.9.0      curl libssh2 version
lib-curl-openssl       1.1.1.9    curl OpenSSL version (1.1.1.9)
lib-curl-zlib          1.2.11     curl zlib version
lib-date-timelib       2018.04    date timelib version
lib-date-zoneinfo      2020.4     zoneinfo ("Olson") database for date
lib-fileinfo-libmagic  533        fileinfo libmagic version
lib-gd                 2.0.35     The gd library
lib-gd-freetype        2.9.1      freetype version for gd
lib-gd-libjpeg         9.0        libjpeg version for gd
lib-gd-libpng          1.6.34     libpng version for gd
lib-gd-libxpm          3.5.12     libxpm version for gd
lib-iconv              1.15       The iconv library
lib-libxml             2.9.10     libxml library version
lib-mbstring-libmbfl   1.3.2      mbstring libmbfl version
lib-mbstring-oniguruma 6.9.4      mbstring oniguruma version
lib-mysqlnd-mysqlnd    5.0.12-dev mysqlnd library version for mysqlnd
lib-openssl            1.1.1.9    OpenSSL 1.1.1i  8 Dec 2020
lib-pcre               10.32      The pcre library
lib-pcre-unicode       11.0.0     PCRE Unicode version support
lib-pdo_mysql-mysqlnd  5.0.12-dev mysqlnd library version for pdo_mysql
lib-pdo_sqlite-sqlite  3.28.0     The pdo_sqlite-sqlite library
lib-zlib               1.2.11     The zlib library
php                    7.3.27     The PHP interpreter
php-64bit              7.3.27     The PHP interpreter, 64bit
php-ipv6               7.3.27     The PHP interpreter, with IPv6 support
php-zts                7.3.27     The PHP interpreter, with Zend Thread Safety

### On which operating system(s) does the issue occur?

- [ ] Linux
- [ ] MacOS
- [X] Windows

### Steps to reproduce the issue.

1. ...
2. ...
3. ...

```php
use Kreait\Firebase;

$factory = (new Firebase\Factory())
    ->withServiceAccount('/path/to/firebase_credentials.com')
    ->withDatabaseUri('https://my-project.firebaseio.com')
;

// ...
```

### Error message/Stack trace

HTTP ERROR 500
This page is not working

**Comment by jeromegamez** [comment] 2021-07-24 15:13
I'm sorry, but I can't provide general support for debugging general hosting platforms/environments. If you want specific support, you'll need to give me more specific information, a general 500 HTTP Status message (which is delivered by the HTTP Server, not PHP) with a copied code snippet from the docs gives no hints on why this might be happening.

Please provide more information 🙏

**Comment by heeshala** [comment] 2021-07-24 15:54
```
<?php

include('dbcon.php');
$merchant_id         = $_POST['merchant_id'];
$order_id             = $_POST['order_id'];
$payhere_amount     = $_POST['payhere_amount'];
$payhere_currency    = $_POST['payhere_currency'];
$status_code         = $_POST['status_code'];
$md5sig                = $_POST['md5sig'];

$merchant_secret = '#secretcode'; // Replace with your Merchant Secret (Can be found on your PayHere account's Settings page)

$local_md5sig = strtoupper (md5 ( $merchant_id . $order_id . $payhere_amount . $payhere_currency . $status_code . strtoupper(md5($merchant_secret)) ) );


$rfid='0001769905';
$userex='';
$add='100.2';
$citiesRef = $database->collection('passenger');
$query = $citiesRef->where('rfid', '=', $rfid);
$snapshot = $query->documents();
$current;

if (($local_md5sig === $md5sig) AND ($status_code == 2) ){
    foreach ($snapshot as $document) {
        $userex= $document->id();
        $current=$document['credits'];
        printf('First: %s' . PHP_EOL, $document['credits']);
    }
    
    $add=(float) $current+(float) $payhere_amount;
    
    if(strlen($userex)>0){
        try {
            $cityRef = $database->collection('passenger')->document($rfid);
       $cityRef->update([
        ['path' => 'credits','value' => $add]
        
    ]);
    echo("Updated"); }
          
          //catch exception
          catch(Exception $e) {
            echo ('Message: ');
          }
        
    
    }else{
        echo("No User");
    }
}


?>
```

**Comment by jeromegamez** [comment] 2021-07-25 08:29
This looks like code related to Firestore, so my guess is that the grpc PHP extension is not installed in your server environment. Please check and make sure it is installed.

I'm going to close this issue now because this seems to be a problem with your setup and not a bug within the SDK, but feel free to add further comments when you can provide a full error message (not just "Error 500").

**Closed as completed by jeromegamez** 2021-07-25 08:29 UTC

**Comment by heeshala** [comment] 2021-07-25 13:50
> This looks like code related to Firestore, so my guess is that the grpc PHP extension is not installed in your server environment. Please check and make sure it is installed.
> 
> I'm going to close this issue now because this seems to be a problem with your setup and not a bug within the SDK, but feel free to add further comments when you can provide a full error message (not just "Error 500").

Does firebase require root access with php

**Comment by jeromegamez** [comment] 2021-07-25 15:17
To install the grpc PHP extension yourself, you usually need root access, yes. If you use a hosting provider, you can ask them if they can install it for you.
