### ISSUE TITLE
Proxy don't work

### ISSUE THREAD

**Issue by erka11234** [kreait/firebase-php#234] opened 2018-08-08 12:36 UTC
## The problem

Proxy don't work.

## Environment

- PHP 7.2.6 
- Firebase 4.15.1

## Details
If i directly connect to database everything works
Proxy don't work

## Code to reproduce issue

code fragments    
class ObjectBase    

```php
<?php  

require __DIR__.'/vendor/autoload.php';  

use Kreait\Firebase\Factory;  
use Kreait\Firebase\ServiceAccount;  


class ObjectBase  
{  

    private $database;  

    public function objectbase()  
    {  
        $serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/private_key.json');  
        var_dump($serviceAccount);  
        $httpConfig = [  
            'proxy' => [
                'http'  => '$adres_for_http',
                'https' => '$adres_for_https',
            ],
            'debug' => true
         ];   
        $firebase = (new Factory)  
            ->withHttpClientConfig($httpConfig)  
            ->withServiceAccount($serviceAccount)  
            ->withDatabaseUri('https://test-48b03.firebaseio.com')  
            ->create();  
        $this->database = $firebase->getDatabase();  
    }  

......

    public function addKey()  
    {  
        $data = $this->database->getReference('blog/posts');  
        return $data->push([  
            'title' => 'new data'  
        ])->getKey();;  
    }  

?>  
```

index

```php
$objectbase = new ObjectBase();  
$objectbase->addKey();  
```

**Comment by jeromegamez** [comment] 2018-08-08 13:01
- Version 1.7.1 is not a valid version for this SDK
- `use Kreait\Firebase\client` -> this class doesn't exist
- "Don't work" is to unspecific to be able to guess what the error was

I'm afraid there are too many unknowns for me to be able to help effectively, the only recommendation coming to my mind right now is adding a `'debug' => true` to the HTTP config array to see if you can get more information out of that.

**Comment by erka11234** [comment] 2018-08-08 13:17
version was misstake 
client wosn't used (it was an attempt to solve the problem)
'debug' => true i use it but probobly in wrong place


( ! ) Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\firebase\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php on line 40
--


1 | 0.4290 | 393984 | {main}( ) | ...\index.php:0
2 | 0.5890 | 2080432 | ObjectBase->addKey( ) | ...\index.php:84
3 | 0.5910 | 2125464 | Kreait\Firebase\Database\Reference->push( ) | ...\class.objectbase.php:85
4 | 0.5910 | 2125464 | Kreait\Firebase\Database\ApiClient->push( ) | ...\Reference.php:353
5 | 0.5910 | 2125736 | Kreait\Firebase\Database\ApiClient->request( ) | ...\ApiClient.php:40
6 | 0.5960 | 2174632 | GuzzleHttp\Client->send( ) | ...\ApiClient.php:62
7 | 0.5970 | 2187760 | GuzzleHttp\Client->sendAsync( ) | ...\Client.php:106
8 | 0.5970 | 2188256 | GuzzleHttp\Client->transfer( ) | ...\Client.php:99
9 | 0.5990 | 2226296 | GuzzleHttp\HandlerStack->__invoke( ) | ...\Client.php:277
10 | 0.6000 | 2238328 | GuzzleHttp\Middleware::GuzzleHttp\{closure}( ) | ...\HandlerStack.php:67
11 | 0.6000 | 2238328 | GuzzleHttp\RedirectMiddleware->__invoke( ) | ...\Middleware.php:60
12 | 0.6000 | 2239096 | GuzzleHttp\Middleware::GuzzleHttp\{closure}( ) | ...\RedirectMiddleware.php:70
13 | 0.6000 | 2239096 | GuzzleHttp\PrepareBodyMiddleware->__invoke( ) | ...\Middleware.php:30
14 | 0.6000 | 2241552 | Google\Auth\Middleware\AuthTokenMiddleware->Google\Auth\Middleware\{closure}( ) | ...\PrepareBodyMiddleware.php:66
15 | 0.6000 | 2241552 | Google\Auth\Middleware\AuthTokenMiddleware->fetchToken( ) | ...\AuthTokenMiddleware.php:102
16 | 0.6000 | 2241552 | Google\Auth\Credentials\ServiceAccountCredentials->fetchAuthToken( ) | ...\AuthTokenMiddleware.php:115
17 | 0.6000 | 2241552 | Google\Auth\OAuth2->fetchAuthToken( ) | ...\ServiceAccountCredentials.php:115
18 | 0.6140 | 2303656 | Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke( ) | ...\OAuth2.php:501
19 | 0.6140 | 2303656 | GuzzleHttp\Client->send( ) | ...\Guzzle6HttpHandler.php:34
20 | 0.6140 | 2303928 | GuzzleHttp\Client->sendAsync( ) | ...\Client.php:106
21 | 0.6140 | 2304200 | GuzzleHttp\Client->transfer( ) | ...\Client.php:99
22 | 0.6140 | 2306408 | GuzzleHttp\HandlerStack->__invoke( ) | ...\Client.php:277
23 | 0.6140 | 2307480 | GuzzleHttp\Middleware::GuzzleHttp\{closure}( ) | ...\HandlerStack.php:67
24 | 0.6140 | 2307480 | GuzzleHttp\RedirectMiddleware->__invoke( ) | ...\Middleware.php:60
25 | 0.6140 | 2308024 | GuzzleHttp\Middleware::GuzzleHttp\{closure}( ) | ...\RedirectMiddleware.php:70
26 | 0.6140 | 2308024 | GuzzleHttp\PrepareBodyMiddleware->__invoke( ) | ...\Middleware.php:30
27 | 0.6140 | 2310832 | GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}( ) | ...\PrepareBodyMiddleware.php:66
28 | 0.6140 | 2310832 | GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}( ) | ...\Proxy.php:51
29 | 0.6140 | 2310832 | GuzzleHttp\Handler\CurlHandler->__invoke( ) | ...\Proxy.php:28

**Comment by erka11234** [comment] 2018-08-08 13:29
![image](https://user-images.githubusercontent.com/16616492/43839946-b4055d1c-9b1f-11e8-937d-cc1dd4eac13f.png)
easier and more readable

**Comment by jeromegamez** [comment] 2018-08-09 08:30
I tried to reproduce the issue, but unfortunately wasn't successful. Here are the two scripts I used to test:

### With `debug` enabled, without Proxy

```php
<?php

declare(strict_types=1);

use Kreait\Firebase;
use Kreait\Firebase\Exception\FirebaseException;

require_once __DIR__.'/vendor/autoload.php';

$serviceAccount = Firebase\ServiceAccount::fromJsonFile(__DIR__.'/tests/_fixtures/test_credentials.json');

$firebase = (new Firebase\Factory())
    ->withServiceAccount($serviceAccount)
    ->withHttpClientConfig([
        'debug' => true,
    ])
    ->create();

$db = $firebase->getDatabase();

try {
    $db->getReference()->getValue();
} catch (FirebaseException $e) {
    echo $e->getMessage();
}
```

This gave me the following result:

```bash
❯ php test.php
*   Trying 35.201.97.85...
* TCP_NODELAY set
* Connected to <edited>.firebaseio.com (35.201.97.85) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=firebaseio.com
*  start date: Aug  1 17:31:49 2018 GMT
*  expire date: Mar 27 00:00:00 2019 GMT
*  subjectAltName: host "<edited>.firebaseio.com" matched cert's "*.firebaseio.com"
*  issuer: C=US; O=Google Trust Services; CN=Google Internet Authority G3
*  SSL certificate verify ok.
> GET /.json HTTP/1.1
Host: <edited>.firebaseio.com
User-Agent: GuzzleHttp/6.3.3 curl/7.54.0 PHP/7.2.8
authorization: Bearer <edited>

< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 09 Aug 2018 08:17:58 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 57788
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Cache-Control: no-cache
< Strict-Transport-Security: max-age=31556926; includeSubDomains; preload
<
* Connection #0 to host <edited>.firebaseio.com left intact
```

### With `debug` enabled, with Proxy configuration

I entered bogus proxy values, so I expect this to fail:

```php
<?php

declare(strict_types=1);

use Kreait\Firebase;
use Kreait\Firebase\Exception\FirebaseException;

require_once __DIR__.'/vendor/autoload.php';

$serviceAccount = Firebase\ServiceAccount::fromJsonFile(__DIR__.'/tests/_fixtures/test_credentials.json');

$firebase = (new Firebase\Factory())
    ->withServiceAccount($serviceAccount)
    ->withHttpClientConfig([
        'debug' => true,
        'proxy' => [
            'http' => 'http://localhost',
            'https' => 'http://localhost'
        ]
    ])
    ->create();

$db = $firebase->getDatabase();

try {
    $db->getReference()->getValue();
} catch (FirebaseException $e) {
    echo $e->getMessage();
}
```

gave me

```bash
❯ php test_poc.php
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 1080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connection failed
* connect to 127.0.0.1 port 1080 failed: Connection refused
* Failed to connect to localhost port 1080: Connection refused
* Closing connection 0
cURL error 7: Failed to connect to localhost port 1080: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

which was expected - but it at least shows that the HTTP client config seem to be correctly passed to the HTTP Client.

Right now, I have no idea why this would fail in your context :/

**Comment by erka11234** [comment] 2018-08-09 09:13
C:\xampp\htdocs\firebase>php test.php
cURL error 7: Failed to connect to www.googleapis.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
C:\xampp\htdocs\firebase>

nothing new

**Comment by erka11234** [comment] 2018-08-09 12:14
In this function this lost $options['proxy']['https']  
if i add $options['proxy']['https'] after function then program is successful  
```php
public function __invoke(RequestInterface $request, array $options)
    {
        $handler = $this->resolve();

        return $handler($request, $options);
    }
```
Have you any idea?

**Comment by erka11234** [comment] 2018-08-09 13:29
What is your version of php i firebase?

**Comment by jeromegamez** [comment] 2018-08-09 13:44
On my local computer, I'm on 7.2.8, but it shouldn't make a difference...

I just stumbled upon this: https://github.com/guzzle/guzzle/issues/1838#issuecomment-338170372 - could that perhaps help?

**Comment by erka11234** [comment] 2018-08-09 13:53
No. It don't work. After function this make array(http => proxy) and still don't connect

**Comment by erka11234** [comment] 2018-08-09 13:55
"name": "guzzlehttp/guzzle",
            "version": "6.3.3",
i have too

**Comment by jeromegamez** [comment] 2018-08-09 17:55
I just tried with a free SSL Proxy from https://www.sslproxies.org with this code

```php
$firebase = (new Firebase\Factory())
    ->withServiceAccount($serviceAccount)
    ->withHttpClientConfig([
        'debug' => true,
        'proxy' => '159.69.91.65:3128'
    ])
    ->create();

$firebase->getDatabase()->getReference('/')->getValue();
```

 and the connection was made via the proxy (shown in the first debug output section):

```
*   Trying 159.69.91.65...
* TCP_NODELAY set
* Connected to 159.69.91.65 (159.69.91.65) port 3128 (#0)
* Establish HTTP proxy tunnel to <edited>.firebaseio.com:443
> CONNECT <edited>.firebaseio.com:443 HTTP/1.1
Host: <edited>.firebaseio.com:443
Proxy-Connection: Keep-Alive

< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=firebaseio.com
*  start date: Aug  1 17:31:49 2018 GMT
*  expire date: Mar 27 00:00:00 2019 GMT
*  subjectAltName: host "<edited>.firebaseio.com" matched cert's "*.firebaseio.com"
*  issuer: C=US; O=Google Trust Services; CN=Google Internet Authority G3
*  SSL certificate verify ok.
> GET /.json HTTP/1.1
Host: <edited>.firebaseio.com
User-Agent: GuzzleHttp/6.3.3 curl/7.54.0 PHP/7.2.8
authorization: Bearer <edited>

< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 09 Aug 2018 17:43:35 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 57788
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Cache-Control: no-cache
< Strict-Transport-Security: max-age=31556926; includeSubDomains; preload
<
* Connection #0 to host 159.69.91.65 left intact
```

A few notes:

- Specifying just `'proxy' => $proxyAddress` should really be fine, there's no need to set `http` because every request will be to a `https`URL anyways
- I noticed in the original post that you wrote `'https' => '$adres_for_https'` - there should be no single quotes (`'`) around the variable name - but I think you know that and this is just something that remained from an edit... just saying it for completeness
- Also in the sake of completeness: please make sure that all environments you run this in are configured the same! PHP in the console could be configured differently than in the context of a browser window - for example you could have PHP 7.2 in the terminal, but XAMPP uses another PHP version with different settings. I'm not sure if perhaps XAMPP is preventing this from working.

I'm really curious why it doesn't work for you, please share here when you find out!

**Comment by erka11234** [comment] 2018-08-10 06:28
the same issue :(

**Comment by erka11234** [comment] 2018-08-10 06:40
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to www.googleapis.com port 443: Timed
out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\firebase\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:185
Stack trace:
#0 C:\xampp\htdocs\firebase\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\xampp\htdocs\firebase\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\xampp\htdocs\firebase\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 C:\xampp\htdocs\firebase\vendor\guzzlehttp\guzzle\src\Handler\Proxy.ph in C:\xampp\htdocs\firebase\vendor\kreait\firebase-php\src\Firebase\Exception\ApiException.php on line 40

Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to www.googleapis.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\firebase\vendor\kreait\firebase-php\src\Firebase\Exception\ApiException.php on line 40

Kreait\Firebase\Exception\ApiException: cURL error 7: Failed to connect to www.googleapis.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\firebase\vendor\kreait\firebase-php\src\Firebase\Exception\ApiException.php on line 40

Call Stack:
    0.4729     382160   1. {main}() C:\xampp\htdocs\firebase\test.php:0
    1.2598    2552952   2. Kreait\Firebase\Database\Reference->getValue() C:\xampp\htdocs\firebase\test.php:20
    1.2598    2552952   3. Kreait\Firebase\Database\Reference->getSnapshot() C:\xampp\htdocs\firebase\vendor\kreait\firebase-php\src\Firebase\Database\Reference.php:286
    1.2598    2552952   4. Kreait\Firebase\Database\ApiClient->get() C:\xampp\htdocs\firebase\vendor\kreait\firebase-php\src\Firebase\Database\Reference.php:323
    1.2598    2552952   5. Kreait\Firebase\Database\ApiClient->request() C:\xampp\htdocs\firebase\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php:26

**Comment by jeromegamez** [comment] 2018-08-10 12:17
I don‘t know what to tell you :/. The stack trace says “Curl Error 7” with a link to http://curl.haxx.se/libcurl/c/libcurl-errors.html which in turn says:

CURLE_COULDNT_CONNECT (7)
Failed to connect() to host or proxy.

It’s a connection problem in your environment - I wish it was in the SDK because then I could fix it, but the problem is not within the SDK.

I recommend trying to test your project in another environment (another Operating system, without XAMPP, with another proxy, inside a container, ...) to see where the problem really is. I assume it has something to to with how XAMPP works, while researching for you, I found a couple of StackOverflow posts that talked about issues with XAMPP.

I’m closing the issue now because it’s nothing I can fix within the SDK, but feel free to add further comments and to share unit findings in case somebody else runs into similar problems.

If you find a solution and share it, I’ll add a section to the troubleshooting docs.

**Closed by jeromegamez** 2018-08-10 12:17 UTC
