### ISSUE TITLE
 Uncaught Error: Class 'Kreait\Firebase\Factory' not found in

### ISSUE THREAD

**Issue by NaqiControl** [kreait/firebase-php#648] opened 2021-08-09 14:06 UTC
### Describe the issue you are experiencing

I have an issue here. my php version 7.4.3 and I am using the latest version which is 5.22 of the library.
and its working perfectly on localhost but not on live server :

`Uncaught Error: Class 'Kreait\Firebase\Factory' not found in`

```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require __DIR__ . '/../../vendor/autoload.php';
use Kreait\Firebase\Factory;

class FirebaseAuthService
   {
       public $auth;
    public function __construct()
    {
        $factory = (new Factory())
            ->withServiceAccount('../pathto/firebase_credentials.json')
            ->withDatabaseUri('https://myprojecturl.firebaseio.com/');
        $this->auth = $factory->createAuth();
     }
    }
```

### Installed packages

```json
{
  "require": {
    "phpoffice/phpspreadsheet": "^1.17.1",
    "guzzlehttp/guzzle": "~6.0",
    "ext-mysqli": "*",
    "ext-json": "*",
    "ext-curl": "*",
    "ext-openssl": "*",
    "monolog/monolog": "^2.2",
    "kreait/firebase-php": "^5.22"
  }
}

```

### PHP version and extensions

Same issue here. my php version 7.4.3 and I am using the latest version which is 5.22 of the library.

### On which operating system(s) does the issue occur?

- [X] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

1. works on local host but not on live server
```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require __DIR__ . '/../../vendor/autoload.php';
use Kreait\Firebase\Factory;

class FirebaseAuthService
{
    public $auth;

    public function __construct()
    {
        $factory = (new Factory())
            ->withServiceAccount('../pathto/firebase_credentials.json')
            ->withDatabaseUri('https://my-projecturl.firebaseio.com/');
        $this->auth = $factory->createAuth();
    }
}

```

### Error message/Stack trace

```
<br />
<b>Fatal error</b>: Uncaught Error: Class 'Kreait\Firebase\Factory' not found in
/path/to/firebase-auth-service.php:13
Stack trace:
thrown in <b>/path/to/firebase-auth-service.php</b> on line <b>13</b><br />
```

**Comment by jeromegamez** [comment] 2021-08-09 17:54
If it's working on your local computer but not the remote server, it must be something related to the server and most likely not a bug in the SDK 😅. I'm closing this issue now since you didn't provide information that leads me to believe otherwise, but the error you get says that the class could not be found - please make sure that the vendor directory is present on the remote server and that you have generated the autoloads.

Running `composer install` if you haven't got a vendor folder, or `composer dumpautoload` If the folder is there could help.

Please feel free to share your findings in additional comments if you find a solution, so that others might benefit from it when they encounter similar problems 🙏

**Closed as completed by jeromegamez** 2021-08-09 17:54 UTC

**Comment by NaqiControl** [comment] 2021-08-09 18:17
@jeromegamez  Yes I have the vendor folder exists please take a look [here](https://i.imgur.com/MotU6mc.png).
defiantly if be able to solve it I will post the solution here.

**Comment by NaqiControl** [comment] 2021-08-09 18:19
please if you need any further info let me know

**Comment by jeromegamez** [comment] 2021-08-09 18:57
You're doing a 

```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require __DIR__ . '/../../vendor/autoload.php';
```

in the file where you define the `FirebaseAuthService` class - is this the entry point of your script, and is it the only script you use?

If you have, for example, an `index.php` file somewhere from which you call this class, you need those three lines only in the `index.php` file, not in every class file you define.

When I assume the following directory structure:

```
|- index.php
|- src/
|------App/
|----------/FirebaseAuthService.php
|- vendor/
```

then you need the `require 'vendor/autoload.php';` only in the index.php file, nowhere else.

Also, in your composer.json, you haven't specified a PHP version, or autoload definitions for your application classes - but then again, I can only guess :)

**Comment by NaqiControl** [comment] 2021-08-09 21:46
Finally I solved the issue.
Thanks for your help and actually you gives me the point for searching.
it was from githup actions CI/CD workflow. I have :
```
- name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
```
I removed that part And I have added ignore composer reqs which is I get it [here ](https://github.com/composer/composer/issues/9529#issuecomment-789108340)and the problem fixed :).

```
- name: install composer packages and ignore platform requirements so firebase php auth can run
        run: composer install --ignore-platform-reqs
```

Thanks again and have a nice day.

**Comment by BaseMax** [comment] 2024-02-15 11:26
same issue.

```
Fatal error: Uncaught Error: Class "Kreait\Firebase\Factory" not found
```

and composer json:
```
{
    "require": {
        "mikecao/flight": "^2.0",
        "phpmailer/phpmailer": "^6.9",
        "grpc/grpc": "^v1.41.0",
        "google/cloud-firestore": "^1.25",
        "google/cloud-core": "^1.47",
        "google/protobuf": "^3.25"
    }
}
```
