### ISSUE TITLE
Can anyone help me to retrieve a single record............. from Firebase using PHP

### ISSUE THREAD

**Issue by niranjanmNani** [kreait/firebase-php#550] opened 2021-01-22 11:39 UTC
$this->db->getReference('users')->orderByValue('email')->equalTo($email)->getValue();

exception : Kreait\Firebase\Exception\Database\UnsupportedQuery Object ( [query:Kreait\Firebase\Exception\Database\UnsupportedQuery:private] =>

**Comment by jeromegamez** [comment] 2021-01-28 22:39
The [`orderByValue()`](https://github.com/kreait/firebase-php/blob/b37ec0fe52334bc97cec60543f4b131a7a9ea2e0/src/Firebase/Database/Reference.php#L148) method doesn't accept a parameter, so doing `->orderByValue('email')` has no effect and should just be `->orderByValue()`.

When you receive an exception like this, a good approach is always to `try` an operation in order to `catch` an error if something goes wrong, like in you example. You can find an example that goes into more detail at https://www.w3schools.com/php/php_exception.asp

In this case, please do this (already including the change that I suggested):

```php
try {
    $this->db->getReference('users')->orderByValue()->equalTo($email)->getValue();
} catch (Throwable $e) { // catching Throwable means catching any error
    echo $e->getMessage(); exit;
}
```

This should then show you a better error message, although the `UnsupportedQuery` already gives a small hint on what's happening here.

If you look at the documentation for the `orderByValue()` method (https://firebase-php.readthedocs.io/en/5.14.1/realtime-database.html#by-value) you will see the note that an index must be defined to be able to order results, I am quite confident that a missing index might be the cause for the error here.

You can read more about Realtime Database Indexing here: https://firebase.google.com/docs/database/security/indexing-data

**Comment by jeromegamez** [comment] 2021-01-29 11:22
As this is not a bug within the SDK, I'm going to close this issue now. If you have more usage questions, please use the [discussions tab](https://github.com/kreait/firebase-php/discussions) or consider [becoming a sponsor](https://github.com/sponsors/jeromegamez/) to gain access to a Slack workspace with individual support.

**Closed by jeromegamez** 2021-01-29 11:22 UTC
