### ISSUE TITLE
Error : Call to private Method

### ISSUE THREAD

**Issue by Denysetya1** [kreait/firebase-php#415] opened 2020-04-24 17:11 UTC
I am using Firebase Admin SDK for PHP v 5.1.1
My problem
Fatal error: Uncaught Error: Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile() from context

I use this method:
$acc = ServiceAccount::fromJsonFile(__DIR__.'/xxx.json');

**Comment by jeromegamez** [comment] 2020-04-24 17:20
Duplicate of https://github.com/kreait/firebase-php/issues/410, https://github.com/kreait/firebase-php/issues/408

**Closed by jeromegamez** 2020-04-24 17:20 UTC
