### ISSUE TITLE
Undefined index [users] while retrieving list of users

### ISSUE THREAD

**Issue by raheelriax** [kreait/firebase-php#168] opened 2018-02-15 09:53 UTC
#### 1. Which version of `kreait/firebase-php` are you using?
4

#### 2. Which version of PHP are you using?
7.0.6

#### 3. What's the issue?
ErrorException (E_NOTICE)
Undefined index: users

#### 4. Code that lead to the issue
IN Kreait\Firebase\Auth File
under the methods listUsers

```php
do {
            $response = $this->client->downloadAccount($batchSize, $pageToken);
            $result = JSON::decode((string)$response->getBody(), true);
 
                foreach ((array)$result['users'] as $userData) {
                    yield UserRecord::fromResponseData($userData);
 
                    if (++$count === $maxResults) {
                        return;
                    }
                }
            $pageToken = $result['nextPageToken'] ?? null;
        } while ($pageToken);
```

**Comment by raheelriax** [comment] 2018-02-15 09:57
I am still not sure what's causing this because that error doesn't make any sense to me because the $reuslt array has a users index in it when I used var_dump($result). Anyhow I was able to solve the problem for the time by making the following changes.

`if (isset($result['users'])) {
                foreach ((array)$result['users'] as $userData) {
                    yield UserRecord::fromResponseData($userData);

                    if (++$count === $maxResults) {
                        return;
                    }
                }
            }`

**Comment by jeromegamez** [comment] 2018-02-15 10:39
Hey @raheelriax, and thanks for taking the time to report this issue!

The problem is (was :)) that it is possible that the last result page doesn't include the `users` field. I had this covered in 3.9.x, somehow it slipped through in 4.0.0, and is now back in 4.0.1, please update, it should be fixed then.

**Closed by jeromegamez** 2018-02-15 10:39 UTC

**Comment by raheelriax** [comment] 2018-02-15 10:41
Thanks man
