### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by kiloki-official** [kreait/firebase-php#655] opened 2021-09-08 21:02 UTC
### Describe the issue you are experiencing

Hi,

On Debian (inside the folder where my php code is), I wrote:

composer require kreait/firebase-php

Then, in my PhP script, I add:

`<?php
require __DIR__.'/vendor/autoload.php';
print("test");
?>`

But I get a 500 ERROR.

Could you please help? 

Thanks

### Installed packages

lcobucci/jwt                       4.1.4   A simple library to work with JSON Web Token and JSON Web Signature
monolog/monolog                    1.2.1   Logging for PHP 5.3
mtdowling/jmespath.php             2.6.1   Declaratively specify how to extract elements from a JSON document
psr/cache                          1.0.1   Common interface for caching libraries
psr/container                      1.1.1   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0   Standard interfaces for event handling.
psr/http-client                    1.0.1   Common interface for HTTP clients
psr/http-message                   1.0.1   Common interface for HTTP messages
psr/log                            2.0.0   Common interface for logging libraries
psr/simple-cache                   1.0.1   Common interfaces for simple caching
ralouphie/getallheaders            3.0.3   A polyfill for getallheaders.
riverline/multipart-parser         2.0.8   One class library to parse multipart content with encoding and cha...
rize/uri-template                  0.3.3   PHP URI Template (RFC 6570) supports both expansion & extraction
symfony/cache                      v5.3.7  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  Generic abstractions related to caching
symfony/config                     v5.3.4  Helps you find, load, combine, autofill and validate configuration...
symfony/dependency-injection       v5.3.7  Allows you to standardize and centralize the way objects are const...
symfony/deprecation-contracts      v2.4.0  A generic function and convention to trigger deprecation notices
symfony/error-handler              v5.3.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.3.7  Provides tools that allow your application components to communica...
symfony/event-dispatcher-contracts v2.4.0  Generic abstractions related to dispatching event
symfony/filesystem                 v5.3.4  Provides basic utilities for the filesystem
symfony/http-client-contracts      v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.3.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.3.7  Provides a structured process for converting a Request into a Resp...
symfony/polyfill-ctype             v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP v...
symfony/polyfill-php80             v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP v...
symfony/polyfill-php81             v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP v...
symfony/service-contracts          v2.4.0  Generic abstractions related to writing services
symfony/var-dumper                 v5.3.7  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.3.7  Allows exporting any serializable PHP data structure to plain PHP ...

### PHP version and extensions

8.0.10

### On which operating system(s) does the issue occur?

- [X] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

composer require kreait/firebase-php

Then, in my PhP script, I add:

`<?php
require __DIR__.'/vendor/autoload.php';
print("test");
?>`

### Error message/Stack trace

HTTP ERROR 500

**Comment by jeromegamez** [comment] 2021-09-08 21:24
Unfortunately, `HTTP ERROR 500` is a message from your webserver and doesn't provide information about the underlying problem occurring in the PHP process.

Since I can't reproduce the problem based on the information you shared, I can only offer suggestions:

Make sure that your project directory (the directory in which your script is located) looks similar to this:

```
├── composer.json
├── composer.lock
├── script.php
└── vendor
```

If you do a `require __DIR__.'/vendor/autoload.php';`, PHP will throw an error and stop executing the file if your script and the `vendor` folder are not in the same directory.

If you're in the context of a webserver and have something like a `public` directory as the webserver root, but the project file is outside of the webserver root, you need to change the `require`.

For example, if your project directory looks like this:

```
├── composer.json
├── composer.lock
├── public
│   └── index.php
└── vendor
```

then, in the `index.php` file, you would need a

```php
<?php
# public/index.php
require __DIR__.'/../vendor/autoload.php';

print "test";
```

Also, the output of your `composer show` doesn't show the `kreait/firebase-php` library as being installed.

I'm going to close this issue now because it doesn't seem related to the SDK. Feel free to add further comments and to share your findings so that others might benefit from them, or to create a new issue when you believe you have found a bug in the SDK - in that case, please provide a reproducible example of the problem or/and meaningful error logs; I can only provide help when I can reproduce a problem or have enough information to understand it 🙏

**Closed as completed by jeromegamez** 2021-09-08 21:24 UTC
