### ISSUE TITLE
5.5 deprecated change seems to be causing problems for me

### ISSUE THREAD

**Issue by sdwru** [kreait/firebase-php#457] opened 2020-07-24 00:09 UTC
```
Calling Kreait\Firebase\Factory::withEnabledDebug() without a Logger continues to enable Guzzle's default debug behaviour to print HTTP debug output to STDOUT, but will trigger a deprecation notice suggesting using a Logger instead.
```
Unfortunately, the above change causes an exception error when I use https://github.com/codeinternetapplications/monolog-stackdriver as my logger in laravel.  Ie. `LOG_CHANNEL=stackdriver`

I am not sure who is to blame exactly.  All I know is this causes `monolog-stackdriver` to produce an error on php 7.3.  As far as I can tell it was working ok before this change.  I am also using `kreait/firebase-laravel` package btw.  Maybe the problem is in there because I don't think I should need to make these changes to use the new std behaviour in `firebase-php` so it should be done in `firebase-laravel`.

I did add the new logger config stuff to config/firebase.php in laravel

This problem is with `FIREBASE_ENABLE_DEBUG, true`.  When I set it to `false` I get the following error.

```
"message": "Unable to create a FirestoreClient: syntax error, unexpected ';', expecting '('",
    "exception": "Kreait\\Firebase\\Exception\\RuntimeException",
    "file": "/var/www/mydomain/kreait/firebase-php/src/Firebase/Factory.php",
    "line": 503,
    "trace": [
```
I'm still scratching my head over what is going on.

**Comment by sdwru** [comment] 2020-07-24 14:23
We are also using the following packages.  It could be a combination of things and we are not having any luck trying to narrow it down to just one package.

https://github.com/kreait/laravel-firebase
https://github.com/codeinternetapplications/monolog-stackdriver
https://github.com/googleapis/google-cloud-php-logging

**Comment by jeromegamez** [comment] 2020-08-23 21:53
Hi @sdwru, and sorry for the late reply.

Unfortunately, I don't see how the deprecation could have caused such a serious issue - it's just™ a deprecation warning after all and should have no effect on running code... EXCEPT (I'm just thinking out loud) that one of the other libraries parses deprecation warnings and stumbles upon... something.

On the other hand, the error is triggered while creating a `FirestoreClient` instance, inside of the constructor of the `FirestoreClient` - I believe the trace could give a clue on what's happening there. `Unexpected <char>` messages usually means an unsupported PHP version - I encountered this in the past when users of the SDK compiled the composer dependencies on their local machines with PHP 7.x, and then deployed the complete codebase to a remote environment with PHP 5...

But I'm just guessing here... I'd be happy if it turns out that this is an error in the SDK (or to hear that you got to the root of the issue in the meantime), so please let me know if there's something I can do to help.

For the time being, I'l close the issue here, please re-open it if the cause indeed lies within the SDK, and feel free to add further comments anyway, I read all of them :)

**Closed by jeromegamez** 2020-08-23 21:53 UTC
