### ISSUE TITLE
Uncaught GuzzleHttp Error

### ISSUE THREAD

**Issue by BenAsbach** [kreait/firebase-php#82] opened 2017-04-23 14:45 UTC
I love your lib - Great work!
But sometimes I get this error:

```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in ../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

Stack trace:
#0 ../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 ../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 ../vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 ../vendor/gu in ../vendor/kreait/firebase-php/src/Firebase/Database/ApiClient.php on line 110
```

Any idea what I did wrong ?

Thanks!

**Comment by jeromegamez** [comment] 2017-04-23 14:49
Hi Ben,

I don't think you did anything wrong - according to https://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLECOULDNTCONNECT it seems to be connection…

> **CURLE_COULDNT_CONNECT (7)**
> Failed to connect() to host or proxy.

The best advice I can give is to turn it off and on again. Everything. 😇

**Comment by BenAsbach** [comment] 2017-04-23 15:51
Hi ! Thanks for your reply ;)
I thought the same but even if I turn off and try it again I'm still facing the same issues.
After I wait a few minutes everything works fine.
But I'm afraid that many of our user are having the same issues and can not connect with the database.
Is there any setting I need to change in the php.ini file or anything else I can do to prevent this issues ?
Thanks!

**Comment by jeromegamez** [comment] 2017-04-25 10:21
Another possibility is that you're behind a proxy which messes things up. Unfortunately there's no way to configure the underlying Guzzle client at the moment.

If you're behind a proxy, you could test the theory by adding a [`proxy` option](http://docs.guzzlephp.org/en/latest/request-options.html#proxy) to [Firebase/Database/ApiClient.php#L75](https://github.com/kreait/firebase-php/blob/master/src/Firebase/Database/ApiClient.php#L75) in your local code (so, inside the vendor directory).

If this solves your issues, the only permanent solution at the moment would be to fork my library, apply the change and [use your fork instead](https://getcomposer.org/doc/05-repositories.md#vcs), until the problem is solved here (by using configurable dependency injection - which is on my todo list).

**Comment by jeromegamez** [comment] 2017-06-01 22:10
I'll close this now, but feel free to add more comments in case you need further help.

**Closed by jeromegamez** 2017-06-01 22:10 UTC
