### ISSUE TITLE
About the sendOobCode

### ISSUE THREAD

**Issue by freedy82** [kreait/firebase-php#756] opened 2023-01-09 04:51 UTC
### Describe the feature you would like to see

I am interesting with the Firebase Auth.
And i want to verify the user was own with a email.(Not yet regsiter)
So
signInWithEmailAndOobCode was suitable for me.
But I can not found any method to send the oob code with email?

**Comment by freedy82** [comment] 2023-01-09 06:08
I try with
$auth->sendEmailVerificationLink("????@???.???");
$auth->sendSignInWithEmailLink("????@???.???");

Both seem not throw error. But I can not get email?

**Comment by jeromegamez** [comment] 2023-01-09 09:06
`sendEmailVerificationLink()` needs the user to exist in the Auth Database - if the user does not exist, an error `No user with email 'xxx@domain.tld'` should be thrown. If you don't get an error, this means the email exists in the Auth database. Another reason could be that error reporting is disabled in your PHP application.

`signInWithEmailLink()` can be used with any email address - I just tested this and received the email.

Based on my own tests I assume right now that the SDK works as intended. Perhaps you could try the following to narrow down the issue:

* Make sure that email + password authentication is enabled in your Firebase Project: https://firebase.google.com/docs/auth/web/email-link-auth#enable_email_link_sign-in_for_your_firebase_project
* Try the `sendEmailVerificationLink()` method with an email address you know doesn't exist in your project, for example, `unknown@example.com` - this should definitely throw an exception.
* Look in your spam folder if the email might be there (this is what happened when I tried this with my test project)

I saw in your GitHub profile that you are located in Hong Kong - in the past, some people have reported that Firebase was (partly) not working for them when using Firebase from China or Iran, perhaps that could be a reason here as well. The fact that you don't receive errors when using the `send*()` methods makes me think that this _could_ be a possibility here as well.

**Comment by freedy82** [comment] 2023-01-09 09:54
Very thank for your fast reply.
Yes. I found the issue.
It seem my company email with "outlook.com" was can not get the email.
But it was can get in spam with gmail.com and hotmail.com.
Really not sure why-_-.

But the seem the "sendSignInWithEmailLink" was very low limit. even the page said have 300 email daily. In my test with 10-20 email already get  QUOTA_EXCEEDED error. 

sendEmailVerificationLink seem better still work for me.

**Comment by jeromegamez** [comment] 2023-01-09 17:03
Unfortunately, the quota exceeded errors and everything else returned by the Firebase APIs is out of my/the SDK's control.

It's possible that the limits get reached faster if you are not the only developer working on the project - but in general, 300 Emails per day seems like a low number to me... can you show me where this is documented?

**Comment by freedy82** [comment] 2023-01-10 03:16
https://firebase.google.com/docs/auth/limits
You can check the document from above

**Comment by jeromegamez** [comment] 2023-01-10 08:23
Thank you for sharing the link! 

Since this doesn't seem to be a problem with the SDK itself, I'm going to close this issue now. Feel free to add further comments in case you want to share findings that might be interesting to others! Thank you!

**Closed as completed by jeromegamez** 2023-01-10 08:23 UTC
