### ISSUE TITLE
request it too slow in a specific  time of day 

### ISSUE THREAD

**Issue by waleedazam** [kreait/firebase-php#53] opened 2016-10-27 14:24 UTC
Hello 
I build some API  depends on data in firebase its work fine all days hours but in mid of day in specific  time it work slow and after it work fine back 
i check my server its work fine and build test serves to test server ( no database connection inside ) and it work fine 
I guess it may some thing happened in connection that cause this problem 
is there is way to test it or check it to find the real reason  ?

**Comment by jeromegamez** [comment] 2016-10-27 15:23
Hey @waleedazam,

you could try using a logger (e.g. Monolog) to log the interaction with the Firebase REST API, quick example:


```php
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

$logger = new Logger('firebase');
$logger->pushHandler(new StreamHandler('firebase.log', Logger::DEBUG));

$config = new Configuration();
$config->setLogger($logger);

$firebase = new Firebase('https://your-project.firebaseio.com', $config);
```

and then check the logs. But I am pretty sure it has nothing to do with the library itself, if the problem occurs only in the mid of day :), and there are too many possibilities what the cause could be, so I'm afraid I can't really help you.

I know this problem from my home internet connection when in the evening, everybody in my neighborhood goes online, then the internet quality goes down. So, if your server is connected to the web through a "normal" internet connection, I would consider moving it to a data center.

Good luck :)

**Closed by jeromegamez** 2016-10-27 15:23 UTC
Labels: 1.x, support

**Comment by waleedazam** [comment] 2016-10-27 16:15
nice trick (the logger) i will use it
