### ISSUE TITLE
PHP Realtime Firebase signInWithEmailAndPassword not working properly

### ISSUE THREAD

**Issue by cedzzz** [kreait/firebase-php#750] opened 2022-11-30 22:33 UTC
### Describe the bug

I am coding a web system with login and register functionality. The login code was working fine yesterday when I coded it, but when I updated some of my code, it suddenly threw some catch exceptions. I reverted the changes that I made but to no avail. The signInWithEmailAndPassword is not working properly. I have tried creating another user and resetting the password but when I tired to log in, it throws an error. Is there any way to fix this?

Here's the code:

```
if(isset($_POST['btn_login']))
{
$email = $_POST['email'];
$clearTextPassword = $_POST['password'];
try{
    $user = $auth->getUserByEmail("$email");
  try{
    $signInResult = $auth->signInWithEmailAndPassword($email, $clearTextPassword);
    $idTokenString = $signInResult->idToken(); 

 
try {
    $verifiedIdToken = $auth->verifyIdToken($idTokenString);
    $uid = $verifiedIdToken->claims()->get('sub');
    $_SESSION['verified_user_id'] = $uid;
    $_SESSION['idTokenString'] = $idTokenString;
    $_SESSION['status'] = "Logged in successfully!";
    header('Location: index.php');
    exit();
} catch (FailedToVerifyToken $e) {
    echo 'The token is invalid: '.$e->getMessage();
}
  } catch (Exception $e){
    $_SESSION['statusred'] = "Invalid Email or Password!";
    header('Location: login.php');
    exit();
  }
} catch (\Kreait\Firebase\Exception\Auth\UserNotFound $e) {
    $_SESSION['statusred'] = "Invalid Email or Password!";
    header('Location: login.php');
    exit();
}
}
```

### Installed packages

```json
{
    "require": {
        "ext-sodium": "*",
        "kreait/firebase-php": "^6.8"
    }
}
```

### PHP version and extensions

```shell
composer-plugin-api    2.1.0    The Composer Plugin API
composer-runtime-api   2.1.0    The Composer Runtime API
ext-bcmath             8.0.12   The bcmath PHP extension
ext-bz2                8.0.12   The bz2 PHP extension
ext-calendar           8.0.12   The calendar PHP extension
ext-ctype              8.0.12   The ctype PHP extension
ext-curl               8.0.12   The curl PHP extension
ext-date               8.0.12   The date PHP extension
ext-dom                20031129 The dom PHP extension
ext-exif               8.0.12   The exif PHP extension
ext-fileinfo           8.0.12   The fileinfo PHP extension
ext-filter             8.0.12   The filter PHP extension
ext-ftp                8.0.12   The ftp PHP extension
ext-gettext            8.0.12   The gettext PHP extension
ext-hash               8.0.12   The hash PHP extension
ext-iconv              8.0.12   The iconv PHP extension
ext-json               8.0.12   The json PHP extension
ext-libxml             8.0.12   The libxml PHP extension
ext-mbstring           8.0.12   The mbstring PHP extension
ext-mysqli             8.0.12   The mysqli PHP extension
ext-mysqlnd            0        The mysqlnd PHP extension (actual version: mysqlnd 8.0.12)
ext-openssl            8.0.12   The openssl PHP extension
ext-pcre               8.0.12   The pcre PHP extension
ext-pdo                8.0.12   The PDO PHP extension
ext-pdo_mysql          8.0.12   The pdo_mysql PHP extension
ext-pdo_sqlite         8.0.12   The pdo_sqlite PHP extension
ext-phar               8.0.12   The Phar PHP extension
ext-readline           8.0.12   The readline PHP extension
ext-reflection         8.0.12   The Reflection PHP extension
ext-session            8.0.12   The session PHP extension
ext-simplexml          8.0.12   The SimpleXML PHP extension
ext-spl                8.0.12   The SPL PHP extension
ext-tokenizer          8.0.12   The tokenizer PHP extension
ext-xml                8.0.12   The xml PHP extension
ext-xmlreader          8.0.12   The xmlreader PHP extension
ext-xmlwriter          8.0.12   The xmlwriter PHP extension
ext-zip                1.19.4   The zip PHP extension
ext-zlib               8.0.12   The zlib PHP extension
lib-bz2                1.0.8    The bz2 library
lib-curl               7.76.1   The curl library
lib-curl-libssh2       1.9.0    curl libssh2 version
lib-curl-openssl       1.1.1.12 curl OpenSSL version (1.1.1.12)
lib-curl-zlib          1.2.11   curl zlib version
lib-date-timelib       2020.03  date timelib version
lib-date-zoneinfo      2021.1   zoneinfo ("Olson") database for date
lib-fileinfo-libmagic  539      fileinfo libmagic version
lib-iconv              1.16     The iconv library
lib-libxml             2.9.10   libxml library version
lib-mbstring-libmbfl   1.3.2    mbstring libmbfl version
lib-mbstring-oniguruma 6.9.7    mbstring oniguruma version
lib-openssl            1.1.1.12 OpenSSL 1.1.1l  24 Aug 2021
lib-pcre               10.35    The pcre library
lib-pcre-unicode       13.0.0   PCRE Unicode version support
lib-pdo_sqlite-sqlite  3.33.0   The pdo_sqlite-sqlite library
lib-zip-libzip         1.7.1    The zip-libzip library
lib-zlib               1.2.11   The zlib library
php                    8.0.12   The PHP interpreter
php-64bit              8.0.12   The PHP interpreter, 64bit
php-ipv6               8.0.12   The PHP interpreter, with IPv6 support
php-zts                8.0.12   The PHP interpreter, with Zend Thread Safety
```

### Steps to reproduce the issue.

```php
if(isset($_POST['btn_login']))
{
$email = $_POST['email'];
$clearTextPassword = $_POST['password'];
try{
    $user = $auth->getUserByEmail("$email");
  try{
    $signInResult = $auth->signInWithEmailAndPassword($email, $clearTextPassword);
    $idTokenString = $signInResult->idToken(); 

 
try {
    $verifiedIdToken = $auth->verifyIdToken($idTokenString);
    $uid = $verifiedIdToken->claims()->get('sub');
    $_SESSION['verified_user_id'] = $uid;
    $_SESSION['idTokenString'] = $idTokenString;
    $_SESSION['status'] = "Logged in successfully!";
    header('Location: index.php');
    exit();
} catch (FailedToVerifyToken $e) {
    echo 'The token is invalid: '.$e->getMessage();
}
  } catch (Exception $e){
    $_SESSION['statusred'] = "Invalid Email or Password!";
    header('Location: login.php');
    exit();
  }
} catch (\Kreait\Firebase\Exception\Auth\UserNotFound $e) {
    $_SESSION['statusred'] = "Invalid Email or Password!";
    header('Location: login.php');
    exit();
}
}
```

### Error message/Stack trace

```shell
-
```

**Comment by cedzzz** [comment] 2022-11-30 23:34
Firebase Authentication also shows that the user signed in when the correct password was given as shown from here.

![image](https://user-images.githubusercontent.com/70250039/204930028-aeb3c469-0752-40a9-afd7-70ac5a994301.png)


Another thing to note is that idTokenString shows up as null when the wrong password was given so I tried letting it show up on the error screen when the correct password was given and here are the results from the 3 accounts that I have created and tried logging in.

Attempt 1:
![image](https://user-images.githubusercontent.com/70250039/204930253-378efe16-28c4-4b47-9262-ee3e963b8f78.png)

Attempt 2:

![image](https://user-images.githubusercontent.com/70250039/204930481-5e4bdd91-c5cd-4f4b-a27b-585033ed004f.png)

Attempt 3:

![image](https://user-images.githubusercontent.com/70250039/204930555-4dea531f-b4e4-4e3d-ad4b-92a96ca85069.png)


Wrong Password:

![image](https://user-images.githubusercontent.com/70250039/204930727-880489e4-46cb-4ddd-ba26-02785f1fac57.png)


Code to show up the value of idTokenString:

```
if(isset($_POST['btn_login']))
{
$email = $_POST['email'];
$clearTextPassword = $_POST['password'];
try{
    $user = $auth->getUserByEmail("$email");
  try{
    $signInResult = $auth->signInWithEmailAndPassword($email, $clearTextPassword);
    $idTokenString = $signInResult->idToken(); 

 
try {
    $verifiedIdToken = $auth->verifyIdToken($idTokenString);
    $uid = $verifiedIdToken->claims()->get('sub');
    $_SESSION['verified_user_id'] = $uid;
    $_SESSION['idTokenString'] = $idTokenString;
    $_SESSION['status'] = "Logged in successfully!";
    header('Location: index.php');
    exit();
} catch (FailedToVerifyToken $e) {
    echo 'The token is invalid: '.$e->getMessage();
}
  } catch (Exception $e){
    $_SESSION['statusred'] = "$idTokenString";
    header('Location: login.php');
    exit();
  }
} catch (\Kreait\Firebase\Exception\Auth\UserNotFound $e) {
    $_SESSION['statusred'] = "Invalid Email or Password!";
    header('Location: login.php');
    exit();
}
}
```

**Comment by jeromegamez** [comment] 2022-12-01 00:43
Unfortunately, your code is not reproducible for me, and I'm convinced that the sign in functionality works in general - you can see that in the Integration Tests, and perhaps you can find there also something to apply to your code.

Some recommendations in general:

- You're currently nesting multiple try/catch blocks - this makes it more difficult to know which operation actually triggered the exception. If you try/catch one operation after another (and don't handle the exceptions while testing), it will be easier to see where an error occurs.
- You don't need to get the user before signing them in. The SignIn result should provide you with the needed information.
- When you sign in a user directly in the code, you don't need to verify the ID Token - ID token verification is only needed when you receive an ID Token from, for example, a Client Application.

I hope this helps 🤞🏻

**Comment by cedzzz** [comment] 2022-12-01 01:17
Thank you for replying! I have changed my try catch blocks and changed the over-all code but when I try to sign in, it says here that my token is not a verified token. 

![image](https://user-images.githubusercontent.com/70250039/204942469-076b584f-359f-4ce3-a3fc-d88200c8b836.png)


Code:

```
if(isset($_POST['btn_login']))
{
$email = $_POST['email'];
$clearTextPassword = $_POST['password'];
try{
    $signInResult = $auth->signInWithEmailAndPassword($email, $clearTextPassword);
    $idTokenString = $signInResult->firebaseUserId();
    $verifiedIdToken = $auth->verifyIdToken($idTokenString);
    $uid = $verifiedIdToken->claims()->get('sub');
    $_SESSION['verified_user_id'] = $uid;
    $_SESSION['idTokenString'] = $idTokenString;
    $_SESSION['status'] = "Logged in successfully!";
    header('Location: index.php');
    exit();
 

} catch (\Kreait\Firebase\Exception\Auth\UserNotFound $e) {
    $_SESSION['statusred'] = "Invalid Email or Password!";
    header('Location: login.php');
    exit();
}
}
```

**Comment by jeromegamez** [comment] 2022-12-01 07:53
Sorry, I should have waited until the next day when I would have been at my computer instead of answering you at 2 a.m. from my mobile phone 😅. Using the `idToken()` method instead of `firebaseUserId()` was correct in your first example.

What I meant with "one operation after another" was not to create one big try/catch block, but wrap every operation in one, sorry if I wasn't clear about that.

I just tried signing in a user with email and password, and it works fine for me (the integration tests of the SDK confirm this). 

Please try this to debug it in your environment:

```php
if(isset($_POST['btn_login']))
{
    $email = $_POST['email'];
    $clearTextPassword = $_POST['password'];

    try {
        $signInResult = $auth->signInWithEmailAndPassword($email, $clearTextPassword);
    } catch (\Kreait\Firebase\Auth\SignIn\FailedToSignIn $e) {
        echo $e->getMessage(); exit;
    }

    $idTokenString = $signInResult->idToken();

    if ($idTokenString === null) {
        echo "User signed in, but ID Token is empty"; exit;
    }

    try {
        $verifiedIdToken = $auth->verifyIdToken($idTokenString);
    } catch (\Kreait\Firebase\Exception\Auth\FailedToVerifyToken $e) {
        echo $e->getMessage(); exit;
    }

    $uid = $verifiedIdToken->claims()->get('sub', 'Not found');
    
    echo "The UID for user with email $email is '$uid'"; exit;
}
```

**Comment by cedzzz** [comment] 2022-12-01 08:39
Again, thank you for replying! I tried your code and it's now working as intended! Thank you so much, there must be a problem in my code. I'll keep this thread open for any future problem. Cheers! 🍻

**Comment by jeromegamez** [comment] 2022-12-01 09:00
Since this was not a bug in the SDK, I will close the issue. Please note that cases like this (not a bug, but 1:1 support on application code) usually is something reserved for Sponsors in one of the Firebase tiers. If you'd like to receive continued 1:1 support, please consider becoming a sponsor 🙏

**Closed as completed by jeromegamez** 2022-12-01 09:00 UTC

**Comment by Cyberfolks** [comment] 2024-08-05 02:45
hi @jeromegamez hope you are doing well.
can you please add error if password/email is wrong/not found in signInWithEmailAndPassword method as for now its simply returning body error with lots of code.
for email i managed with get user by mail method and if user not exists im returning json error in api request but to password i cant handle and its returning 500 error with lots of code. thanks
