### ISSUE TITLE
Syntax errors found in current version

### ISSUE THREAD

**Issue by cssjockey** [kreait/firebase-php#75] opened 2017-04-13 11:00 UTC
syntax error, unexpected ':', expecting ';'  ... 
vendor/kreait/firebase-php/src/Firebase.php on line 24

**Comment by iamtankist** [comment] 2017-04-13 11:03
duplicate of #66

**Closed by iamtankist** 2017-04-13 11:03 UTC

**Comment by cssjockey** [comment] 2017-04-13 11:24
Thanks
