### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Kreait\\Firebase\\Factory' not found 

### ISSUE THREAD

**Issue by hanslbua** [kreait/firebase-php#352] opened 2019-11-12 20:05 UTC
Just entering the example code, but i get this error:

PHP Fatal error:  Uncaught Error: Class 'Kreait\\Firebase\\Factory' not found in test_firebase.php:5

<?php
use Kreait\Firebase;
use Kreait\Firebase\Messaging\CloudMessage;

$messaging = (new Firebase\Factory())->createMessaging();

$message = CloudMessage::withTarget(/* see sections below */)
    ->withNotification(Notification::create('Title', 'Body'))
    ->withData(['key' => 'value']);

$messaging->send($message);
?>

composer.json
{
    "name": "kreait/firebase-php",
    "description": "Firebase Admin SDK",
    "keywords": ["firebase", "google", "sdk", "api", "database"],
    "homepage": "https://github.com/kreait/firebase-php",
    "license": "MIT",
    "authors": [
        {
            "name": "Jérôme Gamez",
            "homepage": "https://github.com/jeromegamez"
        }
    ],
    "support": {
        "docs": "https://firebase-php.readthedocs.io",
        "issues": "https://github.com/kreait/firebase-php/issues",
        "source": "https://github.com/kreait/firebase-php"
    },
    "require": {
        "php": "^7.0",
        "ext-ctype": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "giggsey/libphonenumber-for-php": "^8.9",
        "google/auth": "^0.11.0|^1.0",
        "google/cloud-storage": "^1.14",
        "guzzlehttp/guzzle": "^6.2.1",
        "kreait/clock": "^1.0.1",
        "kreait/firebase-tokens": "^1.8.1",
        "kreait/gcp-metadata": "^1.0.1",
        "lcobucci/jwt": "^3.3.1",
        "mtdowling/jmespath.php": "^2.3",
        "psr/simple-cache": "^1.0",
        "riverline/multipart-parser": "^2.0",
        "superbalist/flysystem-google-storage": "^7.0"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^2.15",
        "jangregor/phpstan-prophecy": "^0.1.2",
        "phpstan/phpstan-phpunit": "^0.9.2",
        "phpunit/phpunit": "^6.0",
        "symfony/var-dumper": "^3.3"
    },
    "suggest": {
        "google/cloud-firestore": "^1.0 to use the Firestore component"
    },
    "autoload": {
        "psr-4": {
            "Kreait\\Firebase\\": "src/Firebase"
        },
        "files": [
            "src/Firebase.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Kreait\\Firebase\\Tests\\": "tests"
        }
    },
    "config": {
        "sort-packages": true,
        "platform": {
            "php": "7.0.33"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "4.x-dev"
        }
    }
}

PHP Version | 7.2.24
System | Linux a2fd9 4.9.0-0.bpo.8-amd64 #1 SMP Debian 4.9.144-3.1~deb8u1 (2019-03-14) x86_64

**Comment by jeromegamez** [comment] 2019-11-12 20:21
This is the composer.json of the SDK, not your project‘s 😅

The error hints that you‘re not using a 4.x release of the library, at least that was the most common reason in previous issues. This happens for instance when you‘re on PHP 5.x instead of 7.x

**Comment by hanslbua** [comment] 2019-11-12 20:23
okay, but i downloaded the latest version from github, and the php version is 7.2. 

so what do i have to do?

**Comment by jeromegamez** [comment] 2019-11-13 07:51
The SDK is expected to be installed via composer as described in https://firebase-php.readthedocs.io/en/stable/overview.html#installation - just downloading it from GitHub will require you to implement your own class autoloader and to download all 3rd party dependencies manually and is not recommended.

**Comment by jeromegamez** [comment] 2019-11-14 11:54
I‘m closing this now because you confirmed on discord that you resolved it 😅

**Closed by jeromegamez** 2019-11-14 11:54 UTC

**Comment by foskert** [comment] 2021-05-26 02:18
hola @jeromegamez  tengo un error con la libreria version kreait/firebase-php 5.0.0  me da error en esta función 'Call to a member function createUser() on null'

**Comment by NaqiControl** [comment] 2021-08-09 13:52
Same issue here. my php version 7.4.3 and I am using the latest version which is 5.22 of the library.
