### ISSUE TITLE
Your client does not have permission to get URL /v1/accounts:signUp from this server

### ISSUE THREAD

**Issue by aschurf** [kreait/firebase-php#765] opened 2023-02-01 14:41 UTC
### Describe the bug

An attempt to create a user fails "Your client does not have permission to get URL /v1/accounts:signUp from this server"
<p>Your client does not have permission to get URL <code>/v1/accounts:signUp</code> from this server.  
<ins>That’s all we know.</ins>

Previously, everything worked fine, users were created, but now it does not work. I also tried creating a new service account in the firebase console, but that didn't help.

### Installed packages

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "ext-curl": "*",
        "ext-dom": "*",
        "ext-gd": "*",
        "ext-simplexml": "*",
        "amocrm/amocrm-api-library": "^0.12.0",
        "barryvdh/laravel-dompdf": "^1.0",
        "dompdf/dompdf": "^1.2",
        "guzzlehttp/guzzle": "^7.2",
        "hflabs/dadata": "^22.3",
        "kreait/firebase-php": "^7.0",
        "laravel/framework": "^9.11",
        "laravel/sanctum": "^2.14.1",
        "laravel/socialite": "^5.5",
        "laravel/tinker": "^2.7",
        "laravel/ui": "^3.4",
        "mpdf/mpdf": "^8.1",
        "phpoffice/phpspreadsheet": "^1.23",
        "spatie/laravel-image-optimizer": "^1.7",
        "symfony/http-client": "^6.1",
        "symfony/mailgun-mailer": "^6.1"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.9",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "platform": {
            "php": "8.1.6"
        },
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "platform-check": false
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

### PHP version and extensions

```shell
php 7.4.3
```

### Steps to reproduce the issue.

```shell
# Insert the commands issued in the terminal if they are needed
# to reproduce the issue. Otherwise, delete this code block.
```

```php
$factory = (new Factory)->withServiceAccount('path/to/serviceAccount.json');

$auth = $factory->createAuth();

$userProperties = [
  'email' => "test@gmail.ru",
  'emailVerified' => false,
  'password' => "password",
  'displayName' =>  "Test",
  'disabled' => false
];

try {
  $createdUser = $auth->createUser($userProperties);
} catch (AuthException $e) {
  dd($e->getMessage());
 //Your client does not have permission to get URL <code>/v1/accounts:signUp</code> from this server.  <ins>That’s all we know.</ins>
}
```

### Error message/Stack trace

```shell
Your client does not have permission to get URL <code>/v1/accounts:signUp</code> from this server.  <ins>That’s all we know.</ins>
```

**Comment by jeromegamez** [comment] 2023-02-01 16:40
Unfortunately, as this is an API response from Firebase, it cannot be handled from within the SDK. If it worked before and now not anymore, it's an additional sign that it's not something within the SDK.

A possible reason could be that the IP address you run the code on is deny-listed by Google's Servers, or that an API has been accidentally disabled (you can check at, for example, https://console.cloud.google.com/apis/library/browse?q=identity%20and%20access%20management%20(iam)%20api). But that's just a guess from the top of my head, and I'm sure you have already looked into this.

If the problem persists (I couldn't reproduce it on my machine), it might be worth asking on StackOverflow or raising a ticket at Google/Firebase directly (this is not an official Admin SDK).

If you're working for a company, you might consider becoming a Sponsor in one of the _Firebase xxx Sponsor_ tiers, then we can look into it together.

Aside from that:
* Your `composer.json` has a requirement of PHP ^8.0.2, you have fixed PHP 8.1.6 in the platform config, but named PHP 7.4.3 in the issue. I'm not sure what that means, but it could be worth looking into.
* As you're in a Laravel 9.x project, have you considered using the [Laravel Package instead of requiring the SDK directly](https://github.com/kreait/laravel-firebase)?

I'm going to close the issue now because it doesn't seem to be a bug in the SDK. Feel free to share your findings in further comments so that others can benefit from them 🤞🏻

**Closed as completed by jeromegamez** 2023-02-01 16:40 UTC
