### ISSUE TITLE
not created access token

### ISSUE THREAD

**Issue by SRLQNL** [kreait/firebase-php#803] opened 2023-06-20 11:59 UTC
### Describe the bug

not created access token when i upload image to firebase storage

### Installed packages

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "google/cloud-firestore": "^1.34",
        "google/cloud-storage": "^1.31",
        "guzzlehttp/guzzle": "^7.2",
        "kreait/laravel-firebase": "^4.2",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

### PHP version and extensions

```shell
php 8
```

### Steps to reproduce the issue.

i can not 

### Error message/Stack trace

```shell
-
```

**Comment by jeromegamez** [comment] 2023-06-20 12:52
I need more information about the problem and code to reproduce it, please.

**Comment by SRLQNL** [comment] 2023-06-20 12:53
<?php

namespace App\Http\Controllers;

use Kreait\Firebase\Contract\Storage;
use Kreait\Firebase\Auth;
use Kreait\Firebase\Factory;
use Google\Cloud\Firestore\FirestoreClient;
use Kreait\Laravel\Firebase\Facades\Firebase;
use Illuminate\Http\Request;

class RegistController extends Controller
{
    public function submit(Request $request){
        $auth = app('firebase.auth');    
        $userProperties = [
        'email' => $request->email,
        'password' => $request->password,
        ];


        $createdUser = $auth->createUser($userProperties);
        $database = app('firebase.firestore')->database()->collection('Users')->document($createdUser->uid);


        $image = $request->file('image');
        $firebase_path = 'Profile_Images/';
        $localfolder = public_path('firebase-temp-uploads').'/';
        $name = $createdUser->uid;
        $extension = $image->getClientOriginalExtension();
        $file = $name.'.'.$extension;
        $image->move($localfolder,$file);
        $uploadedfile = fopen($localfolder.$file,'r');
        $object = app('firebase.storage')->getBucket()->upload($uploadedfile,['name'=>$firebase_path.$file]);
        
        $object->update(
            ['acl' => []],
            ['predefinedAcl' => 'PUBLICREAD']
        );
        
        $database->set([
            'userBio' => $request->message,
            'userBioLink' => $request->number,
            'userEmail' => $request->email,
            'userUID' => $createdUser->uid,
            'username' => $request->name,

        ]);
    }

    public function auth(Request $request){
        
    }
}

**Comment by SRLQNL** [comment] 2023-06-20 12:54
`<?php

namespace App\Http\Controllers;

use Kreait\Firebase\Contract\Storage;
use Kreait\Firebase\Auth;
use Kreait\Firebase\Factory;
use Google\Cloud\Firestore\FirestoreClient;
use Kreait\Laravel\Firebase\Facades\Firebase;
use Illuminate\Http\Request;

class RegistController extends Controller
{
    public function submit(Request $request){
        $auth = app('firebase.auth');    
        $userProperties = [
        'email' => $request->email,
        'password' => $request->password,
        ];


        $createdUser = $auth->createUser($userProperties);
        $database = app('firebase.firestore')->database()->collection('Users')->document($createdUser->uid);


        $image = $request->file('image');
        $firebase_path = 'Profile_Images/';
        $localfolder = public_path('firebase-temp-uploads').'/';
        $name = $createdUser->uid;
        $extension = $image->getClientOriginalExtension();
        $file = $name.'.'.$extension;
        $image->move($localfolder,$file);
        $uploadedfile = fopen($localfolder.$file,'r');
        $object = app('firebase.storage')->getBucket()->upload($uploadedfile,['name'=>$firebase_path.$file]);
        
        $object->update(
            ['acl' => []],
            ['predefinedAcl' => 'PUBLICREAD']
        );
        
        $database->set([
            'userBio' => $request->message,
            'userBioLink' => $request->number,
            'userEmail' => $request->email,
            'userUID' => $createdUser->uid,
            'username' => $request->name,

        ]);
    }

    public function auth(Request $request){
        
    }
}`

**Comment by SRLQNL** [comment] 2023-06-20 12:54
this is my code

**Comment by jeromegamez** [comment] 2023-06-20 13:17
I don't see the problem, where and when are you expecting an access token to be created or used? Please help me help you.

The storage component is just a bridge to the google/cloud-storage library, you can find helpful links to the official docs here: https://firebase-php.readthedocs.io/en/stable/cloud-storage.html

**Comment by SRLQNL** [comment] 2023-06-20 13:22
When i upload image i see problem:error creating access token

**Comment by SRLQNL** [comment] 2023-06-20 19:11
please, it is very important

**Comment by SRLQNL** [comment] 2023-06-20 19:11
help me

**Comment by jeromegamez** [comment] 2023-06-20 20:08
I can't reproduce the problem, but I see you're using version `^4.2` of the package, you could try upgrading to the current `^5.2` and see if this helps.

You can also find a usage example here: https://github.com/jeromegamez/firebase-php-examples/blob/main/src/Command/UploadFileCommand.php - it is a Symfony command, but the Firebase-related code is the same.

Please understand that I cannot provide support without sufficient information, for example, in which line the error occurs or without a stack trace of the error. Also, I'm confident the error message is not thrown by the my package or SDK but from the underlying `google/cloud-storage` library.

**Comment by SRLQNL** [comment] 2023-06-21 11:36
thanks it helped

**Comment by SRLQNL** [comment] 2023-06-21 12:26
how to get download token in php?

**Comment by SRLQNL** [comment] 2023-06-21 12:26
to create a download link

**Comment by jeromegamez** [comment] 2023-06-21 13:35
* https://github.com/jeromegamez/firebase-php-examples/blob/490a8fc33254cac6280bccf4686bd9e5e0674e0e/src/Command/UploadFileCommand.php#L64-L70
* https://github.com/GoogleCloudPlatform/php-docs-samples/blob/main/storage/src/get_object_v4_signed_url.php
* https://github.com/GoogleCloudPlatform/php-docs-samples/blob/main/storage/src/get_object_v2_signed_url.php
* https://cloud.google.com/php/docs/reference/cloud-storage/latest/StorageObject#_Google_Cloud_Storage_StorageObject__signedUrl__

Also have a look at https://github.com/kreait/firebase-php/issues/571 where the same or at least similar issue was posted.

I'm going to close the issue, because it's not a bug or missing feature in the SDK, but feel free to share your findings so that others might benefit from them.

**Closed as not planned by jeromegamez** 2023-06-21 13:35 UTC
